0 0 dataAuditErrors
694 0 SkewEdge: 
712 0 4A.1AB: Minimum DIFFUSION width is 0.16um
722 0 4A.1C.a1_b1:Minimum DIFFUSION to DIFFUSION spacing is 0.20um
732 0 4A.1C.a2_b2: Minimum DIFFUSION to DIFFUSION spacing for 3.3V is 0.22um
745 0 4A.1D.a:Minimum N_WELL to N+ DIFFUSION (1.2V) spacing is 0.3um
746 0 4A.1D.b:Minimum N_WELL to N+ DIFFUSION (3.3V) spacing is 0.5um
754 0 4A.1E:Minimum N_WELL enclosure of N+ DIFFUSION is 0.16um
755 0 4A.1F:Minimum N_WELL to P+ DIFFUSION spacing is 0.16um
768 0 4A.1G.a:Minimum N_WELL enclosure of P+ DIFFUSION (1.2V) is 0.3um
773 0 4A.1G.b:Minimum N_WELL enclosure of P+ DIFFUSION (3.3V) is 0.5um
774 0 4A.1I:Minimum DIFFUSION/isolation area 0.1024 sq.um
782 0 4A.2A.a:Minimum width of an N-Well region is 0.63um
783 0 4A.2A.b:Minimum dimension of an N-Well resistor region is 1.5um
831 0 4A.2A.c:Maximum N-Well width for resistor is 20 um
833 0 4A.2B.a:Minimum N-Well to N-Well spacing is 0.63um
835 0 4A.2B.b1:Minium N-Well to non-potential(1.2V device) N-Well spacing is 1.0um
837 0 4A.2B.b2:Minimum N-Well to non-potential(3.3V device) N-Well spacing is 1.5um
838 0 4A.2B.c_d:Minimum spacing from N-well resistor to other N-Well regions is 2.2um
850 0 4A.2C/D: The resistor marker layer edges must either be entirely coincident with N-well edge or at least partially butted to N+ Tap (terminal).
857 0 4A.4A:Minimum T_WELL width is 0.63um
859 0 4A.4B.a:Minimum T_WELL to T_WELL spacing is 0.63um
861 0 4A.4B.b1:Minimum T_WELL to T_WELL spacing (1.2V) for non-equal-potential is 1.0um
863 0 4A.4B.b2: Minimum T_WELL to T_WELL spacing (3.3V) for non-equal-potential is 1.5um
868 0 4A.4C:Minimum N_WELL enclosure of T_WELL is 1.5um
875 0 4A.4D.a:Minimum T_WELL to P+ DIFFUSION (1.2V) spacing is 0.3um
876 0 4A.4D.b:Minimum T_WELL to P+ DIFFUSION (3.3V) spacing is 0.5um
882 0 4A.4E:Minimum T_WELL enclosure of P+ DIFFUSION is 0.16um
883 0 4A.4F:Minimum T_WELL to N+ DIFFUSION is 0.16um
901 0 4A.4G.a:Minimum T_WELL enclosure of N+ DIFFUSION (1.2V) is 0.3um
906 0 4A.4G.b:Minimum T_WELL enclosure of N+ DIFFUSION (3.3V) is 0.5um
911 0 4A.7A:Minimum width of VTN_SP region is 0.40um
916 0 4A.7B:Minimum space between two VTN_SP regions is 0.40um
928 0 4A.7C:Minimum VTN_SP extension over Poly gate is 0.16um
939 0 4A.7D:Minimum VTN_SP to unrelated Poly gate spacing is 0.28um
944 0 4A.8A: Minimum width of VTP_SP region is 0.40um
949 0 4A.8B: Minimum space between two VTP_SP regions is 0.40um
961 0 4A.8C: Minimum VTP_SP extension over Poly gate is 0.16um
972 0 4A.8D: Minimum VTP_SP to unrelated Poly gate spacing is 0.28um
977 0 4A.9A: Minimum width of VTNH region is 0.40um
982 0 4A.9B: Minimum space between two VTNH regions is 0.40um
994 0 4A.9C: Minimum VTNH extension over Poly gate is 0.16um
1007 0 4A.9D: Minimum VTNH to unrelated Poly gate spacing is 0.28um
1012 0 4A.10A: Minimum width of VTPH region is 0.40um
1017 0 4A.10B: Minimum space between two VTPH regions is 0.40um
1029 0 4A.10C: Minimum VTPH extension over Poly gate is 0.16um
1042 0 4A.10D: Minimum VTPH to unrelated Poly gate spacing is 0.28um
1048 0 4A.11A:Minimum width of poly(1.2V low Vt NMOS) region is 0.12um
1049 0 4A.11B:Minimum width of VTNL region is 0.40um
1051 0 4A.11C:Minimum space between two VTNL regions is 0.40um
1054 0 4A.11D:Minimum VTNL overlap Diffusion is 0.3um
1055 0 4A.11E:Minimum VTNL to unrelated Diffusion spacing is 0.3um
1063 0 4A.11F:Minimum VTNL extension over poly on diffusion of related device is 0.4um
1070 0 4A.11G:Minimum VTNL to unrelated PO1 spacing is 0.4um
1075 0 4A.12A:Minimum width of poly(1.2V low Vt PMOS) region is 0.12um
1076 0 4A.12B:Minimum width of VTPL region is 0.40um
1078 0 4A.12C:Minimum space between two VTPL regions is 0.40um
1081 0 4A.12D:Minimum VTPL overlap Diffusion of related device is 0.3um
1082 0 4A.12E:Minimum VTPL to unrelated Diffusion spacing is 0.3um
1090 0 4A.12F:Minimum VTPL extension over poly on diffusion of related device is 0.4um
1100 0 4A.12G:Minimum VTPL to unrelated PO1 spacing is 0.4um
1108 0 4A.13A:Minimum width of poly(3.3V low Vt NMOS) region is 0.34um
1109 0 4A.13B:Minimum width of VTNHL region is 0.40um
1111 0 4A.13C:Minimum space between two VTNHL regions is 0.40um
1114 0 4A.13D:Minimum VTNHL overlap Diffusion is 0.3um
1115 0 4A.13E:Minimum VTNHL to unrelated Diffusion spacing is 0.3um
1122 0 4A.13F:Minimum VTNHL extension over poly on diffusion of related device is 0.4um
1132 0 4A.13G:Minimum VTPL to unrelated PO1 spacing is 0.4um
1141 0 4A.14A:Minimum width of poly(3.3V low Vt PMOS) region is 0.34um
1142 0 4A.14B:Minimum width of VTPHL region is 0.40um
1144 0 4A.14C:Minimum space between two VTPHL regions is 0.40um
1147 0 4A.14D:Minimum VTPHL overlap Diffusion of related device is 0.3um
1148 0 4A.14E:Minimum VTPHL to unrelated Diffusion spacing is 0.3um
1155 0 4A.14F:Minimum VTPHL extension over poly on diffusion of related device is 0.4um
1165 0 4A.14G:Minimum VTPHL to unrelated PO1 spacing is 0.4um
1168 0 4A.15A.a: Minimum width of poly(1.2V NMOS) region is 1.2um
1170 0 4A.15A.b: Minimum width of poly(3.3V NMOS) region is 1.8um
1176 0 4A.15B: Minimum NATIVE width is 1.60um
1178 0 4A.15C: Minimum NATIVE spacing is 0.63um
1190 0 4A.15D: Exact NATIVE enclosure of DIFFUSION is 0.3um
1191 0 4A.15E: Minimum NATIVE to unrelated Diffusion spacing is 0.25um
1195 0 4A.15F: Minimum NATIVE to N-WELL spacing is 0.9um
1196 0 4A.15J: NATIVE shapes must be orthogonal
1197 0 4A.15K: NATIVE must be within N+
1198 0 4A.Note.1: Two or more device in one Native region is not allowed
1204 0 4A.18A: Minimum width of TG region is 0.45um
1206 0 4A.18B: Minimum space between two TG regions is 0.45um
1208 0 4A.18C: Minimum TG overlap DIFF of 3.3V device is 0.3um
1209 0 4A.18D: Minimum TG to unrelated DIFF spacing is 0.3um
1214 0 4A.18E: Minimum TG extension over PO1 gate of 3.3V device is 0.4um
1217 0 4A.18F: Minimum TG to unrelated PO1 gate spacing is 0.4um
1233 0 4A.19AaBaC: Minimum poly1 width is 0.12um.
1235 0 4A.19Ab: Minimum poly1 width for 3.3V NMOS is 0.34um
1237 0 4A.19Bb: Minimum poly1 width for 3.3V PMOS is 0.30um
1248 0 4A.19D.a1_4A.19D.c1_4A.19D.c2.1: Minimum poly1 spacing is 0.2um.
1249 0 4A.19D.a2: Minimum poly1 spacing on DIFF regions without contact (as poly width >= 0.24um) is 0.24um.
1259 0 4A.19D.b1: Minimum poly1 spacing on DIFF regions with contacts is 0.26um
1260 0 4A.19D.b2: Minimum poly1 spacing on DIFF regions with contacts is 0.3um when PO1 width>0.24um.
1263 0 4A.19D.c2.2: Minimum space between two poly1 regions on field area is 0.24um when PO1 width>0.24um and common run length >1um
1276 0 4A.19E: Minimum overlap of a poly1 region extended into field oxide is 0.18um
1290 0 4A.19F: Minimum separation from an DIFF region to poly1 on field oxide is 0.10um
1302 0 4A.19G: Minimum poly1 endcap to RELATED DIFF spacing is 0.10um
1314 0 4A.19H.a__4A.19O: Minimum poly1 gate to field edge spacing is 0.20um
1333 0 4A.19H.b: Minimum poly1 gate (width > 0.24) to field edge spacing is 0.24 um
1339 0 4A.19I.a: Minimum poly1 gate width for 45 degree(1.2V) is 0.14um
1344 0 4A.19I.b: Minimum poly1 gate width for 45 degree(3.3V) is 0.38um
1358 0 4A.19J: 90 degree bent gate is not allowed.
1359 0 4A.19K: Maximum area of poly1 overlap of DIFF region is 80um x 80um.
1368 0 4A.19N:Minimum PO1 bent gate on field region to DIff spacing is 0.1um
1378 0 4A.19Q: POLY1 may only intersection DIFFUSION at 90 degrees , extra check POLY1 butting edge DIFFUSION
1391 0 4A.20A: Minimum HR width is 0.6um
1393 0 4A.20B: Minimum space between two HR regions is 0.6um
1394 0 4A.20C: Minimum HR poly1 width is 0.5um
1395 0 4A.20D: Minimum SAB width for HR PO1 resistor is 1.0um(define HR POLY length)
1400 0 4A.20E: Minimum HR enclosure of HR poly1 resistor
1401 0 4A.20F: Minimum HR to unrelated poly1 spacing is 2um
1405 0 4A.20G: Minimum HR poly to N+ spacing is 1.5um
1406 0 4A.20H: Minimum HR to PPLUS spacing is 0.5um
1411 0 4A.20I :Minimum SAB overlap HR poly1 resistor is 0.24um , extra check POLY1 inside HR region does not interact SAB
1412 0 4A.20J: Minimum HR poly1 contact to SAB spacing is 0.5um
1416 0 4A.20K: Minimum HR to diffusion spacing is 0.5um
1421 0 4A.20L: Minimum NWELL overlap HR poly1 resistor is 1.5um
1428 0 4A.20M: Min PPLUS overlap SAB is 0.2 um
1431 0 4A.20N: Minimum spacing from P+ implant to unrelated poly resistor is 0.4um
1720 0 4A.21M: Maximum NPLUS diffusion to nearest P+ pick-up spacing is 20um
1726 0 4A.22A: Minimum width of a PPLUS region is 0.24um
1731 0 4A.22B: Minimum space between two PPLUS regions is 0.24um
1737 0 4A.22C.a: Minimum PPLUS overlap P+ DIFF(inside N-Well) is 0.16um
1739 0 4A.22C.b: Minimum PPLUS overlap P+ DIFF(inside P-Well) is 0.06um
1748 0 4A.22D.a: Minimum PPLUS to N+ DIFF spacing(inside P-Well) is 0.16um
1754 0 4A.22D.b: Minimum PPLUS to N+ DIFF spacing(inside N-Well) is 0.06um
1756 0 4A.22E: Minimum P+ diffusion to N+ diffusion is 0um
1757 0 4A.22F(4A.21G): Minimum PPLUS overlap DIFF to form P+ region is 0.16um
1759 0 4A.22G(4A.21F): Minimum DIFF extension over PPLUS to form N+ region is 0.16um
1760 0 4A.22H(4A.21I): Minimum PPLUS to PO1 spacing to form N+ S/D region is 0.24um
1765 0 4A.22I(4A.21H): Minimum PPLUS extension over PO1 to form P+ s/d is 0.24um
1767 0 4A.22J(4A.21K): Minimum PPLUS overlap CONT region is 0.10um, no butted contact.
1768 0 4A.22K(4A.21J): Minimum PPLUS to N+ CONT spacing is 0.10um
1778 0 4A.22L: Soft Contacts are prohibited
2035 0 4A.22M: Maximum P+ DIFF to nearest N+ pick-up spacing is 20um
2036 0 4A.22N: Minimun PPLUS area is 0.1764 sq.um
2057 0 4A.23A: Minimum SAB width is 0.40um
2059 0 4A.23B: Minimum SAB space is 0.40um
2060 0 4A.23C: Contact over SAB is not allowed.
2062 0 4A.23E: Minimum SAB extention over DIFF region is 0.2um
2079 0 4A.23Fa: Minimum SAB to PO1 spacing is 0.24um
2082 0 4A.23Fb: Minimum SAB to PO1 spacing is 0.2um
2083 0 4A.23G:Minimum SAB to unrelated DIFF spacing is 0.20um
2084 0 4A.23H.b: Minimum SAB to PO1 Contact spacing is 0.24um.
2086 0 4A.23J: Minimum SAB extension over DIFF resistor is 0.2um
2088 0 4A.23K: Minimum SAB extension over PO1 resistor is 0.2um
2092 0 4A.23L: Minimum SAB to contact spacing is 0.24um
2094 0 4A.23M: Minimum PPLUS overlap P+ poly1 resistor is 0.24um
2098 0 4A.23N: Minimum PPLUS to N+ (SAB) poly1 resistor spacing is 0.24um
2100 0 4A.23O: Minimum N-Well overlap P+ poly1 non-salicider resistor is 0.24um
2101 0 4A.23P: Minimum N-Well to N+ non-saliceder resistor spacing is 0.24um
2106 0 4A.23Q: Minimum N+ overlap N+ poly1 resistor is 0.24um
2110 0 4A.23R: Minimum N+ to P+ (SAB) poly1 resistor spacing is 0.24um
2111 0 4A.23S: Minimun SAB area is 0.37 sq.um
2120 0 4A.23T: Minimun SAB length for resistor is 1.0um
2123 0 4A.23U: Minimun poly1 width for non-salicide resistor is 0.5um
2126 0 4A.23V: Minimun diffusion width for non-salicide resistor is 0.5um
2127 0 4A.23Wa: Minimun TG to (SAB and PO1) of non-salicide resistor is 0.24um
2128 0 4A.23Wb: Minimun TG to (SAB and DIFF) of non-salicide resistor is 0.24um
2130 0 4A.23Xa: Minimun TG overlap (SAB and PO1) of non-salicide resistor is 0.24um
2132 0 4A.23Xb: Minimun TG overlap (SAB and DIFF) of non-salicide resistor is 0.24um
2143 0 4A.23Ya : N+ DIFFUSION non-salicide resistor should be drawn outside N_WELL
2144 0 4A.23Yb : P+ DIFFUSION non-salicide resistor should be drawn within N_WELL
2145 0 Recommend_4A.23Yc:TG over N+DIFFUSION and P+DIFFUSION non-salicide resistor are not recommended
2146 0 Recommend_4A.23Yd:TG over N+POLY1 and P+POLY1 non-salicide resistor are not recommended
2151 0 4A.23Za:Minimum N+POLY1 non-salicide resistor to P+ implant layer spacing is 0.24um
2152 0 4A.23Zb:Minimum N+ implant layer to  P+POLY1 non-salicide resistor spacing is 0.24um
2154 0 4A.23Zc:Minimum N_WELL layer extension to N+POLY1 non-salicide resistor is 0.24um
2165 0 4A.23Zd.a: Minimum N+ implant enclosure of (N+ POLY1 OVER SAB) is 0.20 um,  (POLY1 endcap is excepted from this rule)
2177 0 4A.23Zd.b: If SAB lies across POLY1,(POLY1 OVER SAB) partially covered,  by N+ and partially not covered by N+ is not allowed
2188 0 4A.23Ze.a: Minimum P+ implant enclosure of ((P+ POLY1 OVER SAB) NOT HR) is 0.20 um,  (POLY1 endcap is excepted from this rule)
2200 0 4A.23Ze.b: If SAB lies across POLY1,((POLY1 OVER SAB) NOT HR) partially covered,  by P+ and partially not covered by P+ is not allowed
2207 0 4A.23Zf.a: Minimum N+ implant enclosure of (N+ DIFFUSION OVER SAB) is 0.20 um,  (DIFFUSION endcap is excepted from this rule)
2214 0 4A.23Zf.b: (DIFFUSION OVER SAB) partially covered by N+ and partially not covered by N+ is not allowed
2221 0 4A.23Zg.a: Minimum P+ implant enclosure of (P+ DIFFUSION OVER SAB) is 0.20 um,  (DIFFUSION endcap is excepted from this rule)
2228 0 4A.23Zg.b: (DIFFUSION OVER SAB) partially covered by P+ and partially not covered by P+ is not allowed
2240 0 4A.24A: Exact CONT size is 0.16um
2250 0 4A.24B: Minimum space between two CONT regions is 0.20um
2261 0 4A.24C.a:Minimum DIFF CONT to poly1 gate spacing is 0.12um.
2262 0 4A.24C.b:Minimum DIFF CONT to poly1(3.3V) gate spacing is 0.14um.
2271 0 4A.24D:Minimum poly1 contact to diffusion spacing is 0.16um
2288 0 4A.24E: Minimum PO1 overlap CONT is 0.06um, no floating contact
2305 0 4A.24FG: Minimum extension of a diffusion region beyond a CONT region is 0.06um
2311 0 4A.24I: Poly contact on diffusion is not allowed.
2318 0 4A.25A: Minimum width of PESD region is 0.60um
2320 0 4A.25B: Minimum space between two PESD regions is 0.60um
2324 0 4A.26A: Minimum width of P_WELL_BLOCK region is 0.63um
2328 0 4A.26B: Minimum space between two P_WELL_BLOCK regions is 0.63um
2334 0 4A.26C: Minimum P_WELL_BLOCK to NATIVE spacing or notch is 0.63 um
2340 0 4A.26D: Minimum P_WELL_BLOCK to N_WELL spacing or notch is 0.90 um
2346 0 4A.26E: Minimum P_WELL_BLOCK to IND spacing or notch is 0.63 um
2349 0 4A.26F: Minimum P_WELL_BLOCK to DIFFUSION spacing is 0.25 um
2356 0 4A.26G: Minimum P_WELL_BLOCK enclosure of DIFFUSION is 0.30 um
2358 0 4A.26H: P_WELL_BLOCK overlap GATE is not allowed
2360 0 4A.26I: P_WELL_BLOCK overlap NWEL is not allowed
2362 0 4A.26J: P_WELL_BLOCK overlap IND is not allowed
2364 0 4A.26K: P_WELL_BLOCK overlap NATIVE is not allowed
2370 0 4A.26L: Minimum IND to NATIVE spacing is 0.63 um
2373 0 4A.26M: Minimum IND to N_WELL spacing is 0.90 um
2379 0 LOGO_5.1A_5.1C_suggested: Minimum width of DIFF region is 0.3um
2382 0 LOGO_5.1B: Minimum space between DIFF regions is 0.4um
2388 0 LOGO_5.2A_5.2C_suggested: Minimum width of NW region is 1.2um
2391 0 LOGO_5.2B: Minimum space between NW regions is 2um
2397 0 LOGO_5.3A_5.3C_suggested: Minimum width of TG region is 0.6um
2400 0 LOGO_5.3B: Minimum space between TG regions is 0.6um
2406 0 LOGO_5.4A_5.4C_suggested: Minimum width of PO1 region is 0.24um
2409 0 LOGO_5.4B: Minimum space between PO1 regions is 0.32um
2415 0 LOGO_5.5A_5.5C_suggested: Minimum width of NPLUS region is 0.42um
2418 0 LOGO_5.5B: Minimum space between NPLUS regions is 0.42um
2424 0 LOGO_5.6A_5.6C_suggested: Minimum width of PPLUS region is 0.42um
2427 0 LOGO_5.6B: Minimum space between PPLUS regions is 0.42um
2433 0 LOGO_5.7A_5.7C_suggested: Minimum width of SAB region is 0.6um
2436 0 LOGO_5.7B: Minimum space between SAB regions is 0.6um
2442 0 LOGO_5.8A_5.8C_suggested: Minimum width of CONT region is 0.32um
2445 0 LOGO_5.8B: Minimum space between CONT regions is 0.4um
2458 0 LOGO_5.8Da: Minimum PO1 enclosure of CONT is 0.14,
2476 0 LOGO_5.8Db: Minimum DIFFUSION enclosure of CONT is 0.14, floating CONT is not allowed
2521 0 SP_4A_1AB:Minimum dimension of an DIFF region is 0.042/0.06um
2531 0 SP_4A_1C.a1b1:Minimum space between two DIFF regions is 0.20um/0.1um;
2532 0 SP_4A_1D.a:Minimum NWEL to a N+ DIFF(1.2V) spacing is 0.26um
2534 0 SP_4A_1G.a:Minimum NWEL overlap P+ DIFF(1.2V) is 0.18um
2535 0 SP_4A_9AaBaC:Minimum PO1 width for 1.2V NMOS or PMOS or interconnect is 0.06um
2538 0 SP_4A_9D.a1:Minimum PO1 spacing on DIFF regions without contact is 0.13um
2539 0 SP_4A_9D.b1:Minimum PO1 spacing on DIFF regions with contact for poly width < 0.24um is 0.26um
2551 0 SP_4A_9D.c1:Minimum space between two PO1 regions on field area is 0.13um/0.07um
2553 0 SP_4A_9E:Minimum overlap of a PO1 region extended into field oxide is 0.03um
2555 0 SP_4A_9G:Minimum PO1 endcap to RELATED DIFF spacing is 0.10um
2556 0 SP_4A_9I.a:Min gate width for 45 degree(1.2V) is 0.14um
2558 0 SP_4A_10C.a:Minimum NPLUS overlap N+ DIFF inside P-Well is 0.13um
2559 0 SP_4A_11B:Minimum space between two PPLUS regions is 0.20um
2560 0 SP_4A_11Da:Minimum PPLUS to N+ DIFF spacing(inside P-Well) is 0.13um
2562 0 SP_4A_11I:Minimum PPLUS implant extension over PO1 to form PPLUS s/d is 0.24um
2564 0 SP_4A_13B:Minimum space between two CONT regions is 0.10um
2565 0 SP_4A_13D:Minimum PO1 CONT to DIFF spaceing is 0.16um
2566 0 SP_4A_15D:Minimum VTNH to unrelated Poly gate spacing is 0.28um
2567 0 SP_4A_16D:Minimum VTPH to unrelated Poly gate spacing is 0.28um
2588 0 DP_4A_1AB:Minimum dimension of an DIFF region is 0.08um
2592 0 DP_4A_1C.a1b1:Minimum space between two DIFF regions is 0.15um/0.07um;
2593 0 DP_4A_1D.a:Minimum NWEL to a N+ DIFF(1.2V) spacing is 0.25um
2595 0 DP_4A_1G.a:Minimum NWEL overlap P+ DIFF(1.2V) is 0.25um
2596 0 DP_4A_9AaBaC:Minimum PO1 width for 1.2V NMOS or PMOS or interconnect is 0.1um
2599 0 DP_4A_9D.a1:Minimum PO1 spacing on DIFF regions without CONT is 0.16um
2600 0 DP_4A_9D.b1:Minimum Poly spacing on diffusion regions with contact for poly width < 0.24um is 0.26um
2603 0 DP_4A_9D.c1:Minimum space between two PO1 regions on field area is 0.12um
2605 0 DP_4A_9E:Minimum overlap of a PO1 region extended into field oxide is 0.02um
2607 0 DP_4A_9H.a:Minimum Poly gate (width <= 0.24) to field edge spacing is 0.01um
2608 0 DP_4A_9I.a:Min gate width for 45 degree(1.2V) is 0.14um
2609 0 DP_4A_9N:Minimum PO1 bent gate on field region to DIffusion spacing = 0.2
2611 0 DP_4A_10C.a:Minimum NPLUS overlap N+ DIFF inside P-Well is 0.13um
2612 0 DP_4A_11B:Minimum space between two PPlus regions is 0.24um
2613 0 DP_4A_11D.a:Minimum PPLUS to N+ DIFF spacing(inside P-Well) is 0.13um
2615 0 DP_4A_11I:Minimum P+ implant extension over Poly to form P+ s/d is 0.24um
2616 0 DP_4A_13B:Minimum space between two CONT regions is 0.20um
2617 0 DP_4A_13C.a:Minimum diffusion CONT to Poly(1.8V) spacing is 0.01um, no contact on gate
2618 0 DP_4A_13D:Minimum PO1 Contact to DIFF spaceing is 0.13um
2620 0 DP_4A_13E:Minimum PO1 overlap CONT is 0.03um, no floating CONT
2621 0 DP_4A_13FG:Minimum extension of an DIFF region beyond a CONT region is 0
2622 0 DP_4A_15D:Minimum VTNH to unrelated Poly gate spacing is 0.28um-->0.25um
2623 0 DP_4A_16D:Minimum VTPH to unrelated Poly gate spacing is 0.28um-->0.25um
2644 0 2PHD_4A_1AB:Minimum dimension of an DIFF region is 0.12um
2651 0 2PHD_4A_1C.a1b1:Minimum space between two DIFF regions is 0.11um
2652 0 2PHD_4A_1D.a:Minimum NWEL to a N+ DIFF(1.2V) spacing is 0.25um
2654 0 2PHD_4A_1G.a:Minimum NWEL overlap P+ DIFF(1.2V) is 0.24um(For Virage's)
2655 0 2PHD_4A_9AaBaC:Minimum PO1 width for 1.2V NMOS or PMOS or interconnect is 0.08um   
2656 0 2PHD_4A_9D.a1:Minimum PO1 spacing on DIFF regions without contact is 0.12um
2657 0 2PHD_4A_9D.b1:Minimum PO1 spacing on DIFF regions with contact for poly width < 0.24um is 0.26um
2666 0 2PHD_4A_9D.c1_1:Minimum space between two PO1 regions on field area is 0.16um
2670 0 2PHD_4A_9D.c1_2:Minimum space between two PO1 regions on field area is 0.12um
2672 0 2PHD_4A_9E:Minimum overlap of a PO1 region extended into field oxide is 0.01um
2674 0 2PHD_4A_9G:Minimum PO1 endcap to RELATED DIFF spacing is 0.01um
2676 0 2PHD_4A_9H.a:Minimum PO1 gate (width <= 0.24) to field edge spacing is 0.04um
2677 0 2PHD_4A_9I.a:Min gate width for 45 degree(1.2V) is 0.14um
2678 0 2PHD_4A_9N:Minimum PO1 bent gate on field region to DIffusion spacing = 0.2
2680 0 2PHD_4A_10C.a:Minimum NPLUS overlap N+ DIFF inside P-Well is 0.16um
2682 0 2PHD_4A_11B:Minimum space between two PPlus regions is 0.24um
2683 0 2PHD_4A_11D.a:Minimum PPLUS implant to N+ DIFF spacing(inside P-Well) is 0.16um
2685 0 2PHD_4A_11I:Minimum PPLUS implant extension over PO1 to form PPLUS s/d is 0.24um
2686 0 2PHD_4A_13B:Minimum space between two CONT regions is 0.20um
2687 0 2PHD_4A_13C.a:Minimum DIFF CONT to PO1(1.2V) spacing is 0.12um, no contact on gate
2688 0 2PHD_4A_13D:Minimum PO1 Contact to DIFF spaceing is 0.06um
2690 0 2PHD_4A_13E:Minimum PO1 overlap CONT is 0.02um, no floating CONT
2692 0 2PHD_4A_13FG:Minimum extension of an DIFF region beyond a CONT region is 0.01
2693 0 2PHD_4A_15D:Minimum VTNH to unrelated Poly gate spacing is 0.28um
2694 0 2PHD_4A_16D:Minimum VTPH to unrelated Poly gate spacing is 0.28um
2716 0 2PRF_4A_1AB:Minimum dimension of an DIFF region is 0.14um
2723 0 2PRF_4A_1C.a1b1_1:Minimum space between two DIFF regions is 0.20um
2725 0 2PRF_4A_1C.a1b1_2:Minimum space between two DIFF regions is 0.15um
2726 0 2PRF_4A_1D.a:Minimum NWEL to a N+ DIFF(1.2V) spacing is 0.25um
2728 0 :Minimum NWEL overlap P+ DIFF(1.2V) is 0.24um
2729 0 2PRF_4A_9AaBaC:Minimum PO1 width for 1.2V NMOS or PMOS or interconnect is 0.08um   
2738 0 2PRF_4A_9D.a1:Minimum PO1 spacing on DIFF regions without contact
2740 0 2PRF_4A_9D.b1:Minimum PO1 spacing on DIFF regions with contactfor  poly width < 0.24um is 0.18um
2749 0 2PRF_4A_9D.c1:Minimum space between two PO1 regions on field area is 0.16um
2751 0 2PRF_4A_9E:Minimum overlap of a PO1 region extended into field oxide is 0.02um
2753 0 2PRF_4A_9H.a:Minimum PO1 gate (width <= 0.24) to field edge spacing is 0.20um
2754 0 2PRF_4A_9I.a:Min gate width for 45 degree(1.2V) is 0.127um
2755 0 2PRF_4A_9N:Minimum PO1 bent gate on field region to DIffusion spacing = 0.04
2757 0 2PRF_4A_10C.a:Minimum NPlus overlap N+ diffusion inside P-Well is 0.16um
2759 0 2PRF_4A_11B:Minimum space between two PPlus regions is 0.24um
2760 0 2PRF_4A_11D.a:Minimum PPLUS implant to N+ DIFF spacing(inside P-Well) is 0.16um
2762 0 2PRF_4A_11I:Minimum PPLUS extension over PO1 to form P+ s/d is 0.2 um
2763 0 2PRF_4A_13B:Minimum space between two CONT regions is 0.19um
2764 0 2PRF_4A_13C.a:Minimum DIFF CONT to Poly(1.2V) spacing is 0.01um, no contact on gate
2765 0 2PRF_4A_13D:Minimum PO1 CONT to DIFF spaceing is 0.03um
2769 0 2PRF_4A_13E:Minimum PO1 overlap CONT is 0 um, no floating CONT
2772 0 2PRF_4A_13FG:Minimum extension of an DIFF region beyond a CONT region is 0.01
2773 0 2PRF_4A_15D:Minimum VTNH to unrelated Poly gate spacing is 0.28um
2774 0 2PRF_4A_16D:Minimum VTPH to unrelated Poly gate spacing is 0.28um
2795 0 2PRF_1_4A_1AB:Minimum dimension of an DIFF region is 0.16um
2796 0 2PRF_1_4A_1C.a1b1:Minimum space between two DIFF regions is 0.20um
2797 0 2PRF_1_4A_1D.a:Minimum NWEL to a N+ DIFF(1.2V) spacing is 0.3um
2799 0 2PRF_1_4A_1G.a:Minimum NWEL overlap P+ DIFF(1.2V) is 0.3um
2800 0 2PRF_1_4A_9AaBaC:Minimum PO1 width for 1.2V NMOS or PMOS or interconnect is 0.12um
2802 0 2PRF_1_4A_9G:Minimum PO1 endcap to RELATED DIFF spacing is 0.10um
2803 0 2PRF_1_4A_9I.a:Min gate width for 45 degree(1.2V) is 0.14um
2805 0 2PRF_1_4A_10C.a:Minimum NPLUS overlap N+ DIFF inside P-Well is 0.16um
2807 0 2PRF_1_4A_11B:Minimum space between two PPLUS regions is 0.24um
2808 0 2PRF_1_4A_11D.a:Minimum PPLUS to N+ DIFF spacing(inside P-Well) is 0.16um
2810 0 2PRF_1_4A_11I:Minimum PPLUS extension over PO1 to form P+ s/d is 0.24um
2811 0 2PRF_1_4A_15D:Minimum VTNH to unrelated Poly gate spacing is 0.28um
2812 0 2PRF_1_4A_16D:Minimum VTPH to unrelated Poly gate spacing is 0.28um
2835 0 SPLL_4A_1AB:Minimum dimension of an DIFF region is 0.042/0.06um
2841 0 SPLL_4A_1C.a1b1-b:Minimum space between two DIFF regions is 0.20um/0.1um;
2842 0 SPLL_4A_1D.a:Minimum NWEL to a N+ DIFF(1.2V) spacing is 0.24um
2844 0 SPLL_4A_1G.a:Minimum NWEL overlap P+ DIFF(1.2V) is 0.24um
2846 0 SPLL_4A_4C:Minimum VTNH extension over PO1 of low leakage device is 0.13um
2848 0 SPLL_4A_5C:Minimum VTPH extension over PO1 of low leakage device is 0.16um
2849 0 SPLL_4A_9AaBaC:Minimum PO1 width for 1.2V NMOS or PMOS or interconnect is 0.06um
2850 0 SPLL_4A_9D_a1:Minimum PO1 spacing on DIFF regions without CONT is 0.13um
2851 0 SPLL_4A_9D.b1:Minimum PO1 spacing on DIFF regions with contact for poly width < 0.24um is 0.26um
2860 0 SPLL_4A_9D.c1:Minimum space between two PO1 regions on field area is 0.13um/0.07um
2862 0 SPLL_4A_9E:Minimum overlap of a PO1 region extended into field oxide is 0.03um
2864 0 SPLL_4A_9G:Minimum PO1 endcap to RELATED DIFF spacing is 0.10um
2866 0 SPLL_4A_10C.a:Minimum NPLUS overlap N+ DIFF inside P-Well is 0.13um
2867 0 SPLL_4A_11B:Minimum space between two PPLUS regions is 0.20um
2868 0 SPLL_4A_11D.a:Minimum PPLUS to N+ DIFF spacing(inside P-Well) is 0.13um
2870 0 SPLL_4A_11I:Minimum PPLUS implant extension over PO1 to form PPLUS s/d is 0.24um
2876 0 SPLL_4A_13B:Minimum space between two CONT regions is 0.10um
2877 0 SPLL_4A_13D:Minimum PO1 CONT to DIFF spaceing is 0.16um
2878 0 SPLL_4A_15D:Minimum VTNH to unrelated Poly gate spacing 0.28->0.23um
2879 0 SPLL_4A_16D:Minimum VTPH to unrelated Poly gate spacing 0.28->0.23um
2900 0 2PRFLL_4A_1AB:Minimum dimension of an DIFF region is 0.14um
2907 0 2PRFLL_4A_1C.a1b1_1:Minimum space between two DIFF regions is 0.20um
2909 0 2PRFLL_4A_1C.a1b1_2:Minimum space between two DIFF regions is 0.15um
2910 0 2PRFLL_4A_1D.a:Minimum NWEL to a N+ DIFF(1.2V) spacing is 0.24um
2912 0 2PRFLL_4A_1G.a:Minimum NWEL overlap P+ DIFF(1.2V) is 0.24um
2913 0 2PRFLL_4A_9AaBaC:Minimum PO1 width for 1.2V NMOS or PMOS or interconnect is 0.08um
2914 0 2PRFLL_4A_9D.a1:Minimum PO1 spacing on DIFF regions without contact
2915 0 2PRFLL_4A_9D.b1:Minimum PO1 spacing on DIFF regions with contact for poly width < 0.24um is 0.18um 
2924 0 2PRFLL_4A_9D.c1:Minimum space between two PO1 regions on field area is 0.16um
2926 0 2PRFLL_4A_9E:Minimum overlap of a PO1 region extended into field oxide is 0.02um
2928 0 2PRFLL_4A_9G:Minimum PO1 endcap to RELATED DIFF spacing is 0.04um
2930 0 2PRFLL_4A_9H.a:Minimum PO1 gate (width <= 0.24) to field edge spacing is 0.20um
2931 0 2PRFLL_4A_9I.a:Min gate width for 45 degree(1.2V) is 0.127um
2932 0 2PRFLL_4A_9N:Minimum PO1 bent gate on field region to DIff spacing = 0.04
2934 0 2PRFLL_4A_10C.a:Minimum NPLUS overlap N+ DIFF inside P-Well is 0.16um
2935 0 2PRFLL_4A_11B:Minimum space between two PPLUS regions is 0.24um
2936 0 2PRFLL_4A_11D.a:Minimum PPLUS to N+ DIFF spacing(inside P-Well) is 0.16um
2938 0 2PRFLL_4A_11I:Minimum PPLUS extension over PO1 to form P+ s/d is 0.2 um
2939 0 2PRFLL_4A_13B:Minimum space between two CONT regions is 0.19um
2940 0 2PRFLL_4A_13C.a:Minimum DIFF CONT to Poly(1.2V) spacing is 0.01um, no CONT on gate
2941 0 2PRFLL_4A_13D:Minimum PO1 CONT to DIFF spaceing is 0.03um
2948 0 2PRFLL_4A_13E:Minimum PO1 overlap CONT is 0.02um, no floating CONT
2951 0 2PRFLL_4A_13FG:Minimum extension of an DIFF region beyond a CONT region is 0.01
2952 0 2PRFLL_4A_15D:Minimum VTNH to unrelated Poly gate spacing is 0.28um
2953 0 2PRFLL_4A_16D:Minimum VTPH to unrelated Poly gate spacing is 0.28um
2974 0 DP2_4A_1AB:Minimum dimension of an DIFF region is 0.16um
2981 0 DP2_4A_1C.a1b1:Minimum space between two DIFF regions is 0.20um
2982 0 DP2_4A_1D.a:Minimum NWEL to a N+ DIFF(1.2V) spacing is 0.3um
2984 0 DP2_4A_1G.a:Minimum NWEL overlap P+ DIFF(1.2V) is 0.3um
2985 0 DP2_4A_9AaBaC:Minimum PO1 width for 1.2V NMOS or PMOS or interconnect is 0.12um
2986 0 DP2_4A_9D.a1:Minimum PO1 spacing on DIFF regions without contact is 0.1um
2987 0 DP2_4A_9D.b1:Minimum PO1 spacing on DIFF regions with contact for poly width < 0.24um is 0.25um
2996 0 DP2_4A_9D.c1:Minimum space between two PO1 regions on field area is 0.20um
2997 0 DP2_4A_9E:Minimum overlap of a PO1 region extended into field oxide is 0.18um
2998 0 DP2_4A_9F:Minimum clearance from an DIFF region to PO1 on field oxide is 0.10um
3000 0 DP2_4A_9G:Minimum PO1 endcap to RELATED DIFF spacing is 0.02um
3001 0 DP2_4A_9I.a:Min gate width for 45 degree(1.2V) is 0.14um
3002 0 DP2_4A_9N:Minimum PO1 bent gate on field region to DIff spacing = 0.2
3004 0 DP2_4A_10C.a:Minimum NPLUS overlap N+ DIFF inside P-Well is 0.16um
3005 0 DP2_4A_11B:Minimum space between two PPlus regions is 0.24um
3006 0 DP2_4A_11D.a:Minimum PPLUS implant to N+ DIFF spacing(inside P-Well) is 0.16um
3008 0 DP2_4A_11I:Minimum PPLUS implant extension over PO1 to form PPLUS s/d is 0.24um
3009 0 DP2_4A_13B:Minimum space between two CONT regions is 0.20um
3010 0 DP2_4A_13C.a:Minimum DIFF CONT to Poly(1.2V) spacing is 0.01um, no contact on gate
3011 0 DP2_4A_13D:Minimum PO1 Contact to DIFF spaceing is 0.16um
3012 0 DP2_4A_13E:Minimum PO1 overlap CONT is 0.06um, no floating conntact
3013 0 DP2_4A_13FG:Minimum extension of an DIFF region beyond a CONT region is 0.06
3014 0 DP2_4A_15D:Minimum VTNH to unrelated Poly gate spacing is 0.28->0.23um
3015 0 DP2_4A_16D:Minimum VTPH to unrelated Poly gate spacing is 0.28->0.23um
3039 0 SP_1_4A_1AB:Minimum dimension of an DIFF region is 0.042/0.06um
3043 0 SP_1_4A_1C.a1b1:Minimum space between two DIFF regions is 0.20um/0.1um;
3044 0 SP_1_4A_1D.a:Minimum NWEL to a N+ DIFF(1.2V) spacing is 0.26um
3046 0 SP_1_4A_1G.a:Minimum NWEL overlap P+ DIFF(1.2V) is 0.18um
3047 0 SP_1_4A_9AaBaC:Minimum PO1 width for 1.2V NMOS or PMOS or interconnect is 0.06um
3050 0 SP_1_4A_9D.a1:Minimum PO1 spacing on DIFF regions without contact is 0.13um
3051 0 SP_1_4A_9D.b1:Minimum PO1 spacing on DIFF regions with contact for poly width < 0.24um is 0.26um
3057 0 SP_1_4A_9D.c1:Minimum space between two PO1 regions on field area is 0.13um/0.07um
3059 0 SP_1_4A_9E:Minimum overlap of a PO1 region extended into field oxide is 0.03um
3061 0 SP_1_4A_9G:Minimum PO1 endcap to RELATED DIFF spacing is 0.10um
3062 0 SP_1_4A_9I.a:Min gate width for 45 degree(1.2V) is 0.14um
3064 0 SP_1_4A_10C.a:Minimum NPLUS overlap N+ DIFF inside P-Well is 0.13um
3065 0 SP_1_4A_11B:Minimum space between two PPLUS regions is 0.20um
3066 0 SP_1_4A_11D.a:Minimum PPLUS to N+ DIFF spacing(inside P-Well) is 0.13um
3068 0 SP_1_4A_11I:Minimum PPLUS implant extension over PO1 to form PPLUS s/d is 0.24um
3070 0 SP_1_4A_13B:Minimum space between two CONT regions is 0.10um
3071 0 SP_1_4A_13D:Minimum PO1 CONT to DIFF spaceing is 0.16um
3072 0 SP_1_4A_15D:Minimum VTNH to unrelated Poly gate spacing is 0.28um
3073 0 SP_1_4A_16D:Minimum VTPH to unrelated Poly gate spacing is 0.28um
3105 0 DPS.4A.1AB_1: Minimum dimension of an DIFF is 0.125 when common run length <=0.055
3113 0 DPS.4A.1AB_2: Minimum dimension of an DIFF is 0.145 when common run length 0.055< x <=0.205
3121 0 DPS.4A.1AB_3: Minimum dimension of an DIFF is 0.155 when common run length 0.205< x <=0.29
3129 0 DPS.4A.1AB_4: Minimum dimension of an DIFF is 0.14 when common run length 0.29< x <=0.3
3137 0 DPS.4A.1AB_5: Minimum dimension of an DIFF is 0.16 when common run length >0.3
3140 0 DPS.4A.1AB_6: Minimum dimension of an DIFF is 0.155 when Corner to Corner
3153 0 DPS.4A.1C.a1b1_1: Minimum space between two DIFF regions is 0.08um when common run length <=0.02
3166 0 DPS.4A.1C.a1b1_2: Minimum space between two DIFF regions is 0.155um when common run length 0.02<X<=0.03
3179 0 DPS.4A.1C.a1b1_3: Minimum space between two DIFF regions is 0.05um when common run length 0.03<X<=0.055
3192 0 DPS.4A.1C.a1b1_4: Minimum space between two DIFF regions is 0.03um when common run length 0.055<X<=0.155
3205 0 DPS.4A.1C.a1b1_5: Minimum space between two DIFF regions is 0.18um when common run length 0.155<X<=0.165
3229 0 DPS.4A.1C.a1b1_6: Minimum space between two DIFF regions is 0.19um when common run length 0.165<X<=0.355
3242 0 DPS.4A.1C.a1b1_7: Minimum space between two DIFF regions is 0.2um when others
3245 0 DPS.4A.1D.a: Minimum NWEL to a N+ DIFF(1.2V) spacing is 0.255um
3259 0 DPS.4A.1E: Minimum NWEL overlap N+ DIFF is 0.15um
3272 0 DPS.4A.1G.a_1: Minimum NWEL overlap P+ DIFF(1.2V) is 0.235um when common run length <=0.02
3285 0 DPS.4A.1G.a_2: Minimum NWEL overlap P+ DIFF(1.2V) is 0.235um when common run length >0.02 <=0.19
3298 0 DPS.4A.1G.a_3: Minimum NWEL overlap P+ DIFF(1.2V) is 0.25um when common run length >0.19 <0.62
3311 0 DPS.4A.1G.a_4: Minimum NWEL overlap P+ DIFF(1.2V) is 0.235um when common run length ==0.62
3324 0 DPS.4A.1G.a_5: Minimum NWEL overlap P+ DIFF(1.2V) is 0.25um when common run length >0.62
3337 0 DPS.4A.2B.a_1: Minimum N-Well to N-Well spacing for equal-potential is 0.46 when common run length ==0.015
3359 0 DPS.4A.2B.a_2: Minimum N-Well to N-Well spacing for equal-potential is 0.63 for others
3369 0 DPS.4A.9AaBaC_1: Minimum PO1 width for 1.2V NMOS or PMOS or interconnect is 0.09um when PO1 interact PG_GATE
3377 0 DPS.4A.9AaBaC_2: Minimum PO1 width for 1.2V NMOS or PMOS or interconnect is 0.045um when common run length <= 0.01
3385 0 DPS.4A.9AaBaC_3: Minimum PO1 width for 1.2V NMOS or PMOS or interconnect is 0.08um when common run length 0.01 <x <= 0.03
3393 0 DPS.4A.9AaBaC_4: Minimum PO1 width for 1.2V NMOS or PMOS or interconnect is 0.045um when common run length 0.03 <x <=0.045
3401 0 DPS.4A.9AaBaC_5: Minimum PO1 width for 1.2V NMOS or PMOS or interconnect is 0.09um when common run length 0.045 <x <=0.12
3412 0 DPS.4A.9AaBaC_6: Minimum PO1 width for 1.2V NMOS or PMOS or interconnect is 0.095um when common run length 0.12 <x <=0.22,  CORNER TO EDGE == 0.095 BYPASS
3420 0 DPS.4A.9AaBaC_7: Minimum PO1 width for 1.2V NMOS or PMOS or interconnect is 0.105um when common run length 0.22 <x <=0.905
3428 0 DPS.4A.9AaBaC_8: Minimum PO1 width for 1.2V NMOS or PMOS or interconnect is 0.12 when common run length >0.905
3440 0 DPS.4A.9D.a1_4A.9D.c1_1: Minimum PO1 spacing on DIFF regions without contact is 0.11 when common run length <=0.055
3452 0 DPS.4A.9D.a1_4A.9D.c1_2: Minimum PO1 spacing on DIFF regions without contact is 0.19um when common run length  0.055<X<=0.09
3464 0 DPS.4A.9D.a1_4A.9D.c1_3: Minimum PO1 spacing on DIFF regions without contact is 0.2um when common run length >0.09
3477 0 DPS.4A.9D.b1_1: Minimum PO1 spacing on DIFF regions with contact,  poly width > 0.24um is 0.19um when common run length =0.09
3490 0 DPS.4A.9D.b1_2: Minimum PO1 spacing on DIFF regions with contact,  poly width > 0.24um is 0.26um when common run length =others
3498 0 DPS.4A.9E_1: Minimum overlap of a PO1 region extended into field oxide is 0.1 um
3506 0 DPS.4A.9E_2: Minimum overlap of a PO1 region extended into field oxide is 0.015um,  When gate area  = 0.01035 or 0.0052125
3516 0 DPS.4A.9E_3: Minimum overlap of a PO1 region extended into field oxide is 0.18um
3530 0 DPS.4A.9F_1: Minimum spacing of DIFF to PO1 on field oxide is 0.01um when common run length <=0.05um
3542 0 DPS.4A.9F_2: Minimum spacing of DIFF to PO1 on field oxide is 0.025um when common run length 0.05< x <=0.6um
3554 0 DPS.4A.9F_3: Minimum spacing of DIFF to PO1 on field oxide is 0.05um when common run length 0.06< x <0.75um
3566 0 DPS.4A.9F_4: Minimum spacing of DIFF to PO1 on field oxide is 0.03um when common run length x ==0.75um
3578 0 DPS.4A.9F_5: Minimum spacing of DIFF to PO1 on field oxide is 0.05um when common run length 0.075< x <=0.08um
3592 0 DPS.4A.9F_6: Minimum spacing of DIFF to PO1 on field oxide is 0.09um when common run length 0.08< x <=0.11um
3620 0 DPS.4A.9F_7a: Minimum spacing of DIFF to PO1 on field oxide is 0.06um when common run length 0.11< x <= 0.12um,  If common run length=0.12,waive quadrangle area = 0.0005 & 0.0035
3632 0 DPS.4A.9F_7b: Minimum spacing of DIFF to PO1 on field oxide is 0.01um when common run length x ==0.12um,  including quadrangle area = 0.0005 & 0.0035
3644 0 DPS.4A.9F_8: Minimum spacing of DIFF to PO1 on field oxide is 0.08um when common run length 0.12< x <=0.14um
3656 0 DPS.4A.9F_9: Minimum spacing of DIFF to PO1 on field oxide is 0.06um when common run length 0.14 < x <=0.145um
3668 0 DPS.4A.9F_10: Minimum spacing of DIFF to PO1 on field oxide is 0.03um when common run length 0.145 < x <=0.155um
3680 0 DPS.4A.9F_11: Minimum spacing of DIFF to PO1 on field oxide is 0.06um when common run length 0.155< x <=0.175um
3692 0 DPS.4A.9F_12: Minimum spacing of DIFF to PO1 on field oxide is 0.085um when common run length 0.175< x <=0.18um
3704 0 DPS.4A.9F_13: Minimum spacing of DIFF to PO1 on field oxide is 0.07um when common run length 0.18< x <=0.2um
3716 0 DPS.4A.9F_14: Minimum spacing of DIFF to PO1 on field oxide is 0.09um,  when common run length 0.2<X<=0.21um,
3728 0 DPS.4A.9F_15: Minimum spacing of DIFF to PO1 on field oxide is 0.1um,  when common run length 0.21<X<0.235um,
3746 0 DPS.4A.9F_16: Minimum spacing of DIFF to PO1 on field oxide is 0.025um,  when common run length ==0.235um and including quadrangle area = 0.0015 & 0.0105
3758 0 DPS.4A.9F_17: Minimum spacing of DIFF to PO1 on field oxide is 0.085um when common run length 0.235< x <= 0.29um
3770 0 DPS.4A.9F_18: Minimum spacing of DIFF to PO1 on field oxide is 0.1 um for others
3776 0 DPS.4A.9F_19: Minimum spacing of DIFF to PO1 on field oxide is 0.06um for Corner to Corner
3780 0 DPS.4A.9G: Minimum PO1 endcap to RELATED DIFF spacing is 0.05um
3786 0 DPS.4A.9H.a__4A.9O_1: Minimum PO1 gate to field edge spacing is 0.005um
3792 0 DPS.4A.9H.a__4A.9O_2: Minimum PO1 gate to field edge spacing is 0.01um
3798 0 DPS.4A.9H.a__4A.9O_3: Minimum PO1 gate to field edge spacing is 0.185um
3804 0 DPS.4A.9H.a__4A.9O_4: Minimum PO1 gate to field edge spacing is 0.074um,  when gate area = 0.0052125 or 0.01035
3810 0 DPS.4A.9H.a__4A.9O_5: Minimum PO1 gate to field edge spacing is 0.01um,  when gate area = 0.0354
3818 0 DPS.4A.9H.a__4A.9O_6: Minimum PO1 gate to field edge spacing is 0.2 um for others
3822 0 DPS.4A.9I.a: Min gate width for 45 degree(1.2V) is 0.125um
3825 0 DPS.4A.9N: Minimum PO1 bent gate on field region to DIffusion spacing = 0.1
3846 0 DPS.4A.10C.a_1: Minimum NPLUS overlap N+ DIFF inside P-Well is 0.14um when common run length =0.43
3877 0 DPS.4A.10C.a_2: Minimum NPLUS overlap N+ DIFF inside P-Well is 0.16um when others
3889 0 DPS.4A.10D.a_1: Minimum NPLUS to P+ DIFF spacing(inside N-Well) is 0.15 when common run length =0.25
3901 0 DPS.4A.10D.a_2: Minimum NPLUS to P+ DIFF spacing(inside N-Well) is 0.16 when others
3911 0 DPS.4A.11C.a_1: Minimum PPLUS overlap P+ DIFF(inside N-Well) is 0.15um when common run length =0.25
3926 0 DPS.4A.11C.a_2: Minimum PPLUS overlap P+ DIFF(inside N-Well) is 0.16um when others
3928 0 DPS.4A.13A: Minimum and maximum width of a CONT region is 0.16um.
3932 0 DPS.4A.13B_1: Minimum space between two CONT regions is 0.16um, when Corner to Corner,  point to edge
3945 0 DPS.4A.13B_2: Minimum space between two CONT regions is 0.185um, when common run length =0.09
3958 0 DPS.4A.13B_3: Minimum space between two CONT regions is 0.2um, when others
3970 0 DPS.4A.13C.a_1: Minimum DIFF CONT to Poly(1.2V) spacing is 0.12um,when common run lenght <0.105
3982 0 DPS.4A.13C.a_2: Minimum DIFF CONT to Poly(1.2V) spacing is 0.095um,when common run lenght ==0.105
3994 0 DPS.4A.13C.a_3: Minimum DIFF CONT to Poly(1.2V) spacing is 0.065um,when common run lenght >0.105 <=0.11
4006 0 DPS.4A.13C.a_4: Minimum DIFF CONT to Poly(1.2V) spacing is 0.12um,when common run lenght >0.11 <0.16
4018 0 DPS.4A.13C.a_5: Minimum DIFF CONT to Poly(1.2V) spacing is 0.095um,when common run lenght ==0.16
4030 0 DPS.4A.13C.a_6: Minimum DIFF CONT to Poly(1.2V) spacing is 0.11um,when common run lenght >0.16
4038 0 DPS.4A.13D_1: Minimum PO1 Contact to DIFF spaceing is 0.065um when corner to edge
4046 0 DPS.4A.13D_2: Minimum PO1 Contact to DIFF spaceing is 0.125um when corner to corner
4058 0 DPS.4A.13D_3: Minimum PO1 Contact to DIFF spaceing is 0.095um,when common run lenght <=0.022
4070 0 DPS.4A.13D_4: Minimum PO1 Contact to DIFF spaceing is 0.12um,when common run lenght 0.022<x<=0.06
4082 0 DPS.4A.13D_5: Minimum PO1 Contact to DIFF spaceing is 0.03um,when common run lenght 0.06<x<=0.095
4094 0 DPS.4A.13D_6: Minimum PO1 Contact to DIFF spaceing is 0.16um,when common run lenght >0.095
4121 0 DPS.4A.13E: Minimum PO1 overlap CONT is 0.06um, no floating conntact,  Size single size -0.06,  By pass (0     0    0.055 0.04),  By pass (0.005 0.01 0.05  0.04),  By pass (0.09  0.12 0.12  0.12),  By pass (0.12  0.12 0.12  0.12)
4184 0 DPS.4A.13FG: Minimum extension of an DIFF region beyond a CONT region is,  Size single size -0.015,  By pass (0.045 0.05  0.035 0.05 ),  By pass (0.025 0.075 0.025 0.075),  By pass (0.07  0.025 0.07  0.025),  By pass (0.00  0.03  0.015 0.045),  By pass (0.015 0.055 0.02  0.075),  By pass (0.07  0.025 0.075 0.035),  By pass (0.045 0.035 0.025 0.075),  By pass (0.025 0.075 0.035 0.075),  By pass (0.015 0.015 0.02  0.065),  By pass (0.075 0.075 0.075 0.075)
4186 0 DPS.4A.13I: Poly contact on diffusion is not allowed.
4195 0 DPS.4B.1A: Minimum width of ME1 region is 0.16um
4198 0 DPS.4B.1D.a: Minimum ME1 overlap contac is 0 um,waive share cont
4251 0 DPS.4B.1D.bc: ME1 enclose CONT at end-of-line or outer corner is 0.06,when ME1 width < 0.24,  Size single size -0.01,   cont (GOOD 0.05  0.07  0.02  0.035 ),   cont (GOOD 0.005 0.015 0.045 0.07  ),   cont (GOOD 0.05  0.07  0.02  0.05),   cont (GOOD 0.02  0.03  0.06  0.06),   cont (GOOD 0.01  0.07  0.01  0.07),   cont (GOOD 0.03  0.07  0.03  0.05),   cont (GOOD 0.03  0.07  0.03  0.07),   cont (GOOD 0.07  0.07  0.07  0.07)
4264 0 DPS.4B.3C: Minimum space between two ME2 regions is 0.19um,when common run lenght =0.44
4277 0 DPS_4B.3C_1: Minimum space between two ME2 regions is 0.20um,when others
4304 0 DP2S.4A.1AB_1: Minimum dimension of an DIFF is 0.13 when common run length <=0.005
4312 0 DP2S.4A.1AB_2: Minimum dimension of an DIFF is 0.1 when common run length 0.005< x <=0.03
4320 0 DP2S.4A.1AB_3: Minimum dimension of an DIFF is 0.08 when common run length 0.03< x <=0.05
4328 0 DP2S.4A.1AB_4: Minimum dimension of an DIFF is 0.135 when common run length 0.05< x <=0.12
4336 0 DP2S.4A.1AB_5: Minimum dimension of an DIFF is 0.12 when common run length 0.12< x <=0.14
4344 0 DP2S.4A.1AB_6: Minimum dimension of an DIFF is 0.16 when common run length >0.16
4347 0 DP2S.4A.1AB_7: Minimum dimension of an DIFF is 0.155 when Corner to Corner
4350 0 DP2S.4A.1AB_8: Minimum dimension of an DIFF is 0.14 when Corner to EDGE
4363 0 DP2S.4A.1C.a1b1_1: Minimum space between two DIFF regions is 0.11um when common run length <=0.025
4376 0 DP2S.4A.1C.a1b1_2: Minimum space between two DIFF regions is 0.07um when common run length 0.025<X<=0.03
4389 0 DP2S.4A.1C.a1b1_3: Minimum space between two DIFF regions is 0.14um when common run length 0.03<X<=0.04
4402 0 DP2S.4A.1C.a1b1_4: Minimum space between two DIFF regions is 0.09um when common run length 0.04<X<=0.05
4472 0 DP2S.4A.1C.a1b1_5: Minimum space between two DIFF regions is 0.165um when common run length 0.05<X<=0.12,  waive notch error( 0.12 0.14 0.04 0.13 0.08 0.01) (0.05 0.065 0.07 0.025 0.12 0.09) (0.025 0.08 0.045 0.03 0.07 0.11)
4504 0 DP2S.4A.1C.a1b1_6: Minimum space between two DIFF regions is 0.19um when common run length 0.12<X<=0.14,  waive notch error( 0.12 0.14 0.04 0.13 0.08 0.01)
4517 0 DP2S.4A.1C.a1b1_7: Minimum space between two DIFF regions is 0.16um when common run length 0.14<X<=0.16
4530 0 DP2S.4A.1C.a1b1_8: Minimum space between two DIFF regions is 0.175um when common run length 0.16<X<=0.215
4543 0 DP2S.4A.1C.a1b1_9: Minimum space between two DIFF regions is 0.19um when common run length 0.215<X<=0.26
4556 0 DP2S.4A.1C.a1b1_10: Minimum space between two DIFF regions is 0.2um when others
4559 0 DP2S.4A.1D.a: Minimum NWEL to a N+ DIFF(1.2V) spacing is 0.24um
4573 0 DP2S.4A.1E: Minimum NWEL overlap N+ DIFF is 0.16um
4586 0 DP2S.4A.1G.a_1: Minimum NWEL overlap P+ DIFF(1.2V) is 0.24um
4594 0 DP2S.4A.9AaBaC_1: Minimum PO1 width for 1.2V NMOS or PMOS or interconnect is 0.1um when common run length <= 0.075
4602 0 DP2S.4A.9AaBaC_2: Minimum PO1 width for 1.2V NMOS or PMOS or interconnect is 0.09um when common run length 0.075 <x <= 0.18
4610 0 DP2S.4A.9AaBaC_3: Minimum PO1 width for 1.2V NMOS or PMOS or interconnect is 0.12 when common run length >0.18
4622 0 DP2S.4A.9D.a1_4A.9D.c1_1: Minimum PO1 spacing on DIFF regions without contact is 0.18 when common run length <=0.015
4634 0 DP2S.4A.9D.a1_4A.9D.c1_2: Minimum PO1 spacing on DIFF regions without contact is 0.17um when common run length  0.015<X<=0.145
4646 0 DP2S.4A.9D.a1_4A.9D.c1_3: Minimum PO1 spacing on DIFF regions without contact is 0.2um when common run length >0.145
4650 0 DP2S.4A.9D.b1: Minimum PO1 spacing on DIFF regions with contact,  poly width <= 0.24um is 0.26um
4658 0 DP2S.4A.9E_1: Minimum overlap of a PO1 region extended into field oxide is 0.03 um when gate area == 0.002
4666 0 DP2S.4A.9E_2: Minimum overlap of a PO1 region extended into field oxide is 0.18um
4678 0 DP2S.4A.9F_1: Minimum spacing of DIFF to PO1 on field oxide is 0.055um when common run length <=0.02um
4690 0 DP2S.4A.9F_2: Minimum spacing of DIFF to PO1 on field oxide is 0.085um when common run length 0.02< x <=0.03um
4702 0 DP2S.4A.9F_3: Minimum spacing of DIFF to PO1 on field oxide is 0.055um when common run length 0.03< x <=0.04um
4714 0 DP2S.4A.9F_4: Minimum spacing of DIFF to PO1 on field oxide is 0.09um when common run length 0.04< x <=0.08um
4726 0 DP2S.4A.9F_5: Minimum spacing of DIFF to PO1 on field oxide is 0.08um when common run length 0.08< x <=0.11um
4738 0 DP2S.4A.9F_6: Minimum spacing of DIFF to PO1 on field oxide is 0.01um when common run length 0.11< x <=0.13um
4750 0 DP2S.4A.9F_7: Minimum spacing of DIFF to PO1 on field oxide is 0.085um when common run length 0.13< x <=0.185um
4762 0 DP2S.4A.9F_8: Minimum spacing of DIFF to PO1 on field oxide is 0.07um when common run length 0.185< x <=0.28um
4774 0 DP2S.4A.9F_9: Minimum spacing of DIFF to PO1 on field oxide is 0.1um when common run length x >0.28um
4786 0 DP2S.4A.9G: Minimum PO1 endcap to RELATED DIFF spacing is 0.055um
4792 0 DP2S.4A.9H.a__4A.9O_1: Minimum (PO1 gate = PL_GATE_DS2S )to field edge spacing is 0.02um
4798 0 DP2S.4A.9H.a__4A.9O_2: Minimum (PO1 gate = PD_GATE_DS2S ) to field edge spacing is 0.115um
4804 0 DP2S.4A.9H.a__4A.9O_3: Minimum (PO1 gate = PG_GATE_DS2S ) to field edge spacing is 0.04um
4810 0 DP2S.4A.9H.a__4A.9O_4: Minimum PO1 gate to field edge spacing is 0.18um,  when gate area = 0.002
4817 0 DP2S.4A.9H.a__4A.9O_5: Minimum PO1 gate to field edge spacing is 0.2 um for others
4820 0 DP2S.4A.9N: Minimum PO1 bent gate on field region to DIffusion spacing = 0.1
4822 0 DP2S.4A.13A: Minimum and maximum width of a CONT region is 0.16um.
4832 0 DP2S.4A.13B: Minimum space between two CONT regions is 0.20um
4835 0 DP2S.4A.13C.a_1: Minimum DIFF CONT to Poly(1.2V) spacing is 0.02um, for Corner to Corner
4847 0 DP2S.4A.13C.a_2: Minimum DIFF CONT to Poly(1.2V) spacing is 0.11um,when common run lenght <= 0.06
4859 0 DP2S.4A.13C.a_3: Minimum DIFF CONT to Poly(1.2V) spacing is 0.105um,when common run lenght >0.06 <=0.16
4874 0 DP2S.4A.13C.a_4: Minimum DIFF CONT to Poly(1.2V) spacing is 0.12um,for others
4900 0 DP2S.4A.13D: Minimum PO1 Contact to DIFF spaceing is 0.16um,  Corner to Coner = 0.135 by pass
4933 0 DP2S.4A.13E: Minimum PO1 overlap CONT is 0.06um, no floating conntact,  Size single size -0.06,  By pass (0     0.04    0  0.07),  By pass (0.06  0.06 0.06  0.06),  By pass (0.07  0.06 0.07  0.05),  By pass (0.06  0.07 0.06  0.06),  By pass (0.07  0.07 0.07  0.07)
4981 0 DP2S.4A.13FG: Minimum extension of an DIFF region beyond a CONT region is,  Size single size -0.015,  By pass (0.02 0.06 0.06 0.06 ),  By pass (0.03 0.06 0.06 0.06 ),  By pass (0.01 0.05 0.04 0.02 ),  By pass (0.06 0.04 0.01 0.03 ),  By pass (0.02 0.06 0.02 0.06 ),  By pass (0.03 0.05 0.02 0.05 ),  By pass (0.02 0.05 0.01 0.05 ),  By pass (0.06 0.06 0.06 0.06 )
4983 0 DP2S.4A.13I: Poly contact on diffusion is not allowed.
4987 0 DP2S.4B.1A: Minimum width of ME1 region is 0.16um,  waive vilolate area = 0.008663
4991 0 DP2S.4B.1C: Minimum space between ME1 regions is 0.15um
4993 0 DP2S.4B.1D.a: Minimum ME1 overlap contact is 0um, no CONT outside ME1
5019 0 DP2S.4B.1D.bc: ME1 enclose CONT at end-of-line or outer corner is 0.06,when ME1 width < 0.24,   cont (GOOD 0.03  0.04  0.03  0.06 ),   cont (GOOD 0.02  0.06  0.04  0.06),   cont (GOOD 0.06  0.06  0.06  0.06),   cont (GOOD 0.02  0.06  0.06  0.06)
5066 0 4B.1A: Minimum width of ME1 region is 0.16um
5070 0 4B.1B: Maximum width of ME1 region is 25um
5077 0 4B.1C: Minimum space between ME1 regions is 0.16um
5090 0 4B.1C.a: Minimum space between ME1 regions is 0.26 where one ME1 width > 1.76um
5098 0 4B.1D.a: Minimum ME1 overlap contac is 0um, no CONT outside ME1
5112 0 4B.1D.bc: Minimum metal enclosure of CONT at end-of-line or outer corner is 0.06um when metal-1 width < 0.24um
5144 0 4B.1D.d Metal1 (EOL) overlap of contact for M1 width < 0.18um and spacing to three adjacent M1 <= 0.18um is 0.10um
5148 0 4B.1E: Minimum area of ME1 region 0.1024 sq.um
5150 0 4B.1F: Minimum ME1 enclosed area 0.3072 sq.um
5156 0 4B.3A: Minimum width of ME2 region is 0.2um
5160 0 4B.3B: Maximum width of ME2 region is 25um
5165 0 4B.3C: Minimum space between ME2 regions is 0.2um
5178 0 4B.3C.a: Minimum space between ME2 regions is 0.28 where one ME2 width > 2um
5180 0 4B.3D_M: Minimum ME2 overlap contac is 0um, no VI1 outside ME2
5182 0 4B.3E: Minimum area of ME2 region 0.1024 sq.um
5184 0 4B.3F: Minimum ME2 enclosed area 0.3072 sq.um
5190 0 4B.5A: Minimum width of ME3 region is 0.2um
5194 0 4B.5B: Maximum width of ME3 region is 25um
5198 0 4B.5C: Minimum space between ME3 regions is 0.2um
5211 0 4B.5C.a: Minimum space between ME3 regions is 0.28 where one ME3 width > 2um
5213 0 4B.5D_M: Minimum ME3 overlap contac is 0um, no VI1 outside ME3
5215 0 4B.5E: Minimum area of ME3 region 0.1024 sq.um
5217 0 4B.5F: Minimum ME3 enclosed area 0.3072 sq.um
5223 0 4B.7A: Minimum width of ME4 region is 0.2um
5227 0 4B.7B: Maximum width of ME4 region is 25um
5231 0 4B.7C: Minimum space between ME4 regions is 0.2um
5244 0 4B.7C.a: Minimum space between ME4 regions is 0.28 where one ME4 width > 2um
5246 0 4B.7D_M: Minimum ME4 overlap contac is 0um, no VI1 outside ME4
5248 0 4B.7E: Minimum area of ME4 region 0.1024 sq.um
5250 0 4B.7F: Minimum ME4 enclosed area 0.3072 sq.um
5256 0 4B.9A: Minimum width of ME5 region is 0.2um
5260 0 4B.9B: Maximum width of ME5 region is 25um
5264 0 4B.9C: Minimum space between ME5 regions is 0.2um
5277 0 4B.9C.a: Minimum space between ME5 regions is 0.28 where one ME5 width > 2um
5279 0 4B.9D_M: Minimum ME5 overlap contac is 0um, no VI1 outside ME5
5281 0 4B.9E: Minimum area of ME5 region 0.1024 sq.um
5283 0 4B.9F: Minimum ME5 enclosed area 0.3072 sq.um
5289 0 4B.11A: Minimum width of ME6 region is 0.2um
5293 0 4B.11B: Maximum width of ME6 region is 25um
5297 0 4B.11C: Minimum space between ME6 regions is 0.2um
5310 0 4B.11C.a: Minimum space between ME6 regions is 0.28 where one ME6 width > 2um
5312 0 4B.11D_M: Minimum ME6 overlap contac is 0um, no VI1 outside ME6
5314 0 4B.11E: Minimum area of ME6 region 0.1024 sq.um
5316 0 4B.11F: Minimum ME6 enclosed area 0.3072 sq.um
5322 0 4B.13A: Minimum width of ME7 region is 0.4um
5326 0 4B.13B: Maximum width of ME7 region is 25um
5330 0 4B.13C: Minimum space between ME7 regions is 0.4um
5343 0 4B.13C.a: Minimum space between ME7 regions is 0.5 where one ME7 width > 1.6um
5345 0 4B.13D: Minimum ME7 overlap contac is 0um, no VI6 outside ME7
5347 0 4B.13E_20KA: Minimum area of ME7 region 1.0 sq.um
5349 0 4B.13F: Minimum ME7 enclosed area 0.87 sq.um
5355 0 4B.15A_20KA: Minimum width of ME8 region is 1.5um
5359 0 4B.15C_20KA: Minimum space between ME8 regions is 1.5um
5372 0 4B.15C.a_20KA: Minimum space between ME8 regions is 1.5 where one ME8 width > 1.6um
5379 0 4B.15D_20KA: Minimum ME8 overlap contac is 0um, no VI1 outside ME8
5381 0 4B.15E_20KA: Minimum area of ME8 region 2.25 sq.um
5383 0 4B.15F_20KA: Minimum ME8 enclosed area 5.76 sq.um
5390 0 4B.2A__4B.21.2.3M.VI1: Minimum and maximum width of a VI1 region is 0.20um
5398 0 4B.2B.a: Minimum space between two VI1 regions  is 0.20um
5416 0 4B.2B.b: For FSG process, minimum space between two via regions of a via array is 0.28um
5422 0 4B.2C.a: Minimum metal-1 enclosure of via1 is -0.02um, no via1 outside metal-1
5424 0 4B.2C.b: Minimum metal-1( width >= 0.2um ) enclosure of via1 is 0, no via1 outside metal-1
5434 0 4B.2C.cd: Minimum metal-1 enclosure of via1 at end-of-line or outer corner is 0.06um when metal-1 width < 0.24um
5441 0 4B.2C.e: Minimum metal1 (EOL) enclosure of via for metal-1 width < 0.18um and spacing to three adjacent M1 <= 0.18um is 0.10um
5466 0 4B.2D: When metal-1 or metal-2 width > 1.4um, it takes 2 via-1s with spacing <= 0.6um to connect metal-1 and metal-2
5469 0 4B.2E: Via1 edges should be horizontal or vertical
5475 0 4B.4A__4B.21.2.3M.VI2: Minimum and maximum width of a VI2 region is 0.20um
5483 0 4B.4B.a: Minimum space between two VI2 regions  is 0.20um
5501 0 4B.4B.b: For FSG process, minimum space between two via regions of a via array is 0.28um
5503 0 4B.4C.a_M: Minimum metal-2 enclosure of via2 is 0um, no via2 outside metal-2
5510 0 4B.4C.bc_M : Minimum metal-2 enclosure of via2 at end-of-line or outer corner is 0.06um when metal-2 width < 0.24um
5535 0 4B.4D: When metal-2 or metal-3 width > 1.4um, it takes 2 via-1s with spacing <= 0.6um to connect metal-2 and metal-3
5538 0 4B.4E: Via2 edges should be horizontal or vertical
5544 0 4B.6A__4B.21.2.3M.VI3: Minimum and maximum width of a VI3 region is 0.20um
5552 0 4B.6B.a: Minimum space between two VI3 regions  is 0.20um
5570 0 4B.6B.b: For FSG process, minimum space between two via regions of a via array is 0.28um
5571 0 4B.6C.a_M: Minimum metal-3 enclosure of via3 is 0um, no via3 outside metal-3
5578 0 4B.6C.bc_M : Minimum metal-3 enclosure of via3 at end-of-line or outer corner is 0.06um when metal-3 width < 0.24um
5603 0 4B.6D: When metal-3 or metal-4 width > 1.4um, it takes 2 via-1s with spacing <= 0.6um to connect metal-3 and metal-4
5606 0 4B.6E: Via3 edges should be horizontal or vertical
5612 0 4B.8A__4B.21.2.3M.VI4: Minimum and maximum width of a VI4 region is 0.20um
5620 0 4B.8B.a: Minimum space between two VI4 regions  is 0.20um
5638 0 4B.8B.b: For FSG process, minimum space between two via regions of a via array is 0.28um
5639 0 4B.8C.a_M: Minimum metal-4 enclosure of via4 is 0um, no via4 outside metal-4
5646 0 4B.8C.bc_M : Minimum metal-4 enclosure of via4 at end-of-line or outer corner is 0.06um when metal-4 width < 0.24um
5671 0 4B.8D: When metal-4 or metal-5 width > 1.4um, it takes 2 via-1s with spacing <= 0.6um to connect metal-4 and metal-5
5674 0 4B.8E: Via4 edges should be horizontal or vertical
5680 0 4B.10A__4B.21.2.3M.VI5: Minimum and maximum width of a VI5 region is 0.20um
5688 0 4B.10B.a: Minimum space between two VI5 regions  is 0.20um
5706 0 4B.10B.b: For FSG process, minimum space between two via regions of a via array is 0.28um
5707 0 4B.10C.a_M: Minimum metal-5 enclosure of via5 is 0um, no via5 outside metal-5
5714 0 4B.10C.bc_M : Minimum metal-5 enclosure of via5 at end-of-line or outer corner is 0.06um when metal-5 width < 0.24um
5739 0 4B.10D: When metal-5 or metal-6 width > 1.4um, it takes 2 via-1s with spacing <= 0.6um to connect metal-5 and metal-6
5742 0 4B.10E: Via5 edges should be horizontal or vertical
5745 0 4B.12A__4B.21.2.3S.VI6: Minimum and maximum width of a VI6 region is 0.40um
5753 0 4B.12B.a: Minimum space between two VI6 regions  is 0.40um
5771 0 4B.12B.b: For FSG process, minimum space between two via regions of a via array is 0.5um
5773 0 4B.12C : Minimum metal-6 enclosure of via6 is 0um, no via6 outside metal-6
5776 0 4B.12D: Via6 edges should be horizontal or vertical
5779 0 4B.14A_20KA: Minimum and maximum width of a VI7 region is 0.60um
5787 0 4B.14B_20KA: Minimum space between two VI7 regions  is 0.75um
5794 0 4B.14C_20KA : Minimum metal-7 enclosure of via7 is 0.2um, no via7 outside metal-7
5797 0 4B.21.2.3S.VI7: Minimum and maximum width of a VI7 region is 0.40um
5805 0 4B.14B.a: Minimum space between two VI7 regions  is 0.40um
5807 0 4B.14C : Minimum metal-7 enclosure of via7 is 0um, no via7 outside metal-7
5825 0 4B.14B.b: For FSG process, minimum space between two via regions of a via array is 0.5um
5828 0 4B.14D: Via7 edges should be horizontal or vertical
5847 0 4B.2F: Viafarm density of via1 <= 30%
5867 0 4B.4F: Viafarm density of via2 <= 30%
5887 0 4B.6F: Viafarm density of via3 <= 30%
5907 0 4B.8F: Viafarm density of via4 <= 30%
5927 0 4B.10F: Viafarm density of via5 <= 30%
5947 0 4B.12F: Viafarm density of via6  <= 30%
5967 0 4B.14F: Viafarm density of via7  <= 30%
5977 0 4B.14E_TV_20KA: Viafarm density of via7 <= 30%
5980 0 4B.16B_M1: Maximum width of metal-1 over M1SLMK is 10um
5983 0 4B.17B_M2: Maximum width of metal-2 over M2SLMK is 10um
5986 0 4B.17B_M3: Maximum width of metal-3 over M3SLMK is 10um
5989 0 4B.17B_M4: Maximum width of metal-4 over M4SLMK is 10um
5992 0 4B.17B_M5: Maximum width of metal-5 over M5SLMK is 10um
5995 0 4B.17B_M6: Maximum width of metal-6 over M6SLMK is 10um
5998 0 4B.18B_M7: Maximum width of metal-7 over M7SLMK is 10um
6001 0 4B.18B_M8: Maximum width of metal-8 over M8SLMK is 10um
6009 0 Warning_4B_21_1_PAD1: PAD mark layer only can draw in PAD area
6020 0 Warning_4B_21_1_PAD2: One chip include 2 kind of PAD structure is not allowed
6050 0 4B.21.2.3 C: Minimum ME8 enclosure of TMV_RDL is 2.0um, no TMV_RDL outside ME8
6054 0 4B.21.2.3 H.ME8 : Pad ME8 has the same size as AL_RDL pad
6058 0 4B.21.2.3 H.ME7 : Pad ME7 has the same size as AL_RDL pad
6062 0 4B.21.2.3 H.ME6 : Pad ME6 has the same size as AL_RDL pad
6066 0 4B.21.2.3 H.ME5 : Pad ME5 has the same size as AL_RDL pad
6070 0 4B.21.2.3 H.ME4 : Pad ME4 has the same size as AL_RDL pad
6074 0 4B.21.2.3 H.ME3 : Pad ME3 has the same size as AL_RDL pad
6078 0 4B.21.2.3 H.ME2 : Pad ME2 has the same size as AL_RDL pad
6082 0 4B.21.2.3 H.ME1 : Pad ME1 has the same size as AL_RDL pad
6083 0 4B.21.2.3 I.ME8 : Minimum width of a ME8 slot region is 1.2um X 1.2um
6084 0 4B.21.2.3 I.ME7 : Minimum width of a ME7 slot region is 1.2um X 1.2um
6085 0 4B.21.2.3 I.ME6 : Minimum width of a ME6 slot region is 1.2um X 1.2um
6086 0 4B.21.2.3 I.ME5 : Minimum width of a ME5 slot region is 1.2um X 1.2um
6087 0 4B.21.2.3 I.ME4 : Minimum width of a ME4 slot region is 1.2um X 1.2um
6088 0 4B.21.2.3 I.ME3 : Minimum width of a ME3 slot region is 1.2um X 1.2um
6089 0 4B.21.2.3 I.ME2 : Minimum width of a ME2 slot region is 1.2um X 1.2um
6090 0 4B.21.2.3 I.ME1 : Minimum width of a ME1 slot region is 1.2um X 1.2um
6098 0 4B.21.2.3 J.ME8 : Exact space between two ME8 slot regions is 2.8um
6106 0 4B.21.2.3 J.ME7 : Exact space between two ME7 slot regions is 2.8um
6114 0 4B.21.2.3 J.ME6 : Exact space between two ME6 slot regions is 2.8um
6122 0 4B.21.2.3 J.ME5 : Exact space between two ME5 slot regions is 2.8um
6130 0 4B.21.2.3 J.ME4 : Exact space between two ME4 slot regions is 2.8um
6138 0 4B.21.2.3 J.ME3 : Exact space between two ME3 slot regions is 2.8um
6146 0 4B.21.2.3 J.ME2 : Exact space between two ME2 slot regions is 2.8um
6154 0 4B.21.2.3 J.ME1 : Exact space between two ME1 slot regions is 2.8um
6159 0 4B.21.2.3 K.a.ME8 : Minimum metal-8 enclosure of ME8 slot is 2.76um
6164 0 4B.21.2.3 K.a.ME7 : Minimum metal-8 enclosure of ME7 slot is 2.76um
6169 0 4B.21.2.3 K.a.ME6 : Minimum metal-8 enclosure of ME6 slot is 2.76um
6174 0 4B.21.2.3 K.a.ME5 : Minimum metal-8 enclosure of ME5 slot is 2.76um
6179 0 4B.21.2.3 K.a.ME4 : Minimum metal-8 enclosure of ME4 slot is 2.76um
6184 0 4B.21.2.3 K.a.ME3 : Minimum metal-8 enclosure of ME3 slot is 2.76um
6189 0 4B.21.2.3 K.a.ME2 : Minimum metal-8 enclosure of ME2 slot is 2.76um
6194 0 4B.21.2.3 K.a.ME1 : Minimum metal-8 enclosure of ME1 slot is 2.76um
6212 0 4B.21.2.3 K.ME8: Maximun metal-8 enclosure of metal-8 slot is 6.76um
6230 0 4B.21.2.3 K.ME7: Maximun metal-7 enclosure of metal-7 slot is 6.76um
6248 0 4B.21.2.3 K.ME6: Maximun metal-6 enclosure of metal-6 slot is 6.76um
6266 0 4B.21.2.3 K.ME5: Maximun metal-5 enclosure of metal-5 slot is 6.76um
6284 0 4B.21.2.3 K.ME4: Maximun metal-4 enclosure of metal-4 slot is 6.76um
6302 0 4B.21.2.3 K.ME3: Maximun metal-3 enclosure of metal-3 slot is 6.76um
6320 0 4B.21.2.3 K.ME2: Maximun metal-2 enclosure of metal-2 slot is 6.76um
6338 0 4B.21.2.3 K.ME1: Maximun metal-1 enclosure of metal-1 slot is 6.76um
6339 0 4B.21.2.3 L: Metal-8 slot over TMV_RDL is not allowed
6342 0 4B.21.2.3 N.a.VI1: Minimum space between two VI1 regions in pad area is 0.28um
6347 0 4B.21.2.3 O.a.VI1: Minimum VI1 to pad edge regions is 0.1um
6352 0 4B.21.2.3 PQ.VI1: Minimum via1 to metal-1 slot spacing is 0.2um, no via1 on metal-1 slot
6355 0 4B.21.2.3 N.a.VI2: Minimum space between two VI2 regions in pad area is 0.28um
6360 0 4B.21.2.3 O.a.VI2: Minimum VI2 to pad edge regions is 0.1um
6365 0 4B.21.2.3 PQ.VI2: Minimum via2 to metal-2 slot spacing is 0.2um, no via2 on metal-2 slot
6368 0 4B.21.2.3 N.a.VI3: Minimum space between two VI3 regions in pad area is 0.28um
6373 0 4B.21.2.3 O.a.VI3: Minimum VI3 to pad edge regions is 0.1um
6378 0 4B.21.2.3 PQ.VI3: Minimum via3 to metal-3 slot spacing is 0.2um, no via3 on metal-3 slot
6381 0 4B.21.2.3 N.a.VI4: Minimum space between two VI4 regions in pad area is 0.28um
6386 0 4B.21.2.3 O.a.VI4: Minimum VI4 to pad edge regions is 0.1um
6391 0 4B.21.2.3 PQ.VI4: Minimum via4 to metal-4 slot spacing is 0.2um, no via4 on metal-4 slot
6394 0 4B.21.2.3 N.a.VI5: Minimum space between two VI5 regions in pad area is 0.28um
6399 0 4B.21.2.3 O.a.VI5: Minimum VI5 to pad edge regions is 0.1um
6404 0 4B.21.2.3 PQ.VI5: Minimum via5 to metal-5 slot spacing is 0.2um, no via5 on metal-5 slot
6407 0 4B.21.2.3T.a.VI7: Minimum space between two VI7 regions is 0.5um
6412 0 4B.21.2.3 U.a.VI7: Minimum via7 to pad edge regions is 0.1um
6417 0 4B.21.2.3 VW.VI7: Minimum via7 to metal-7 slot spacing is 0.2um, no via7 on metal-7 slot 
6420 0 4B.21.2.3T.a.VI6: Minimum space between two VI6 regions is 0.5um
6425 0 4B.21.2.3 U.a.VI6: Minimum via6 to pad edge regions is 0.1um
6430 0 4B.21.2.3 VW.VI6: Minimum via6 to metal-6 slot spacing is 0.2um, no via6 on metal-6 slot 
6431 0 4B.21.2.3 Y.VI1: Minimum VI1 DENSITY under pad open is 12%
6432 0 4B.21.2.3 Y.VI2: Minimum VI2 DENSITY under pad open is 12%
6433 0 4B.21.2.3 Y.VI3: Minimum VI3 DENSITY under pad open is 12%
6434 0 4B.21.2.3 Y.VI4: Minimum VI4 DENSITY under pad open is 12%
6435 0 4B.21.2.3 Y.VI5: Minimum VI5 DENSITY under pad open is 12%
6436 0 4B.21.2.3 Y.VI6: Minimum VI6 DENSITY under pad open is 12%
6437 0 4B.21.2.3 Y.VI7: Minimum VI7 DENSITY under pad open is 12%
6439 0 Warning_VASS_PAD_M8SLOT: PAD Meatl Must insert Slot 
6441 0 Warning_VASS_PAD_M7SLOT: PAD Meatl Must insert Slot 
6443 0 Warning_VASS_PAD_M6SLOT: PAD Meatl Must insert Slot 
6445 0 Warning_VASS_PAD_M5SLOT: PAD Meatl Must insert Slot 
6447 0 Warning_VASS_PAD_M4SLOT: PAD Meatl Must insert Slot 
6449 0 Warning_VASS_PAD_M3SLOT: PAD Meatl Must insert Slot 
6451 0 Warning_VASS_PAD_M2SLOT: PAD Meatl Must insert Slot 
6490 0 4B.21.3.3C : Minimum ME8 ovelap TMV_RDL is 2.0um, no TMV_RDL outside ME8
6494 0 4B.21.3.3H : Meatl pad has the same size as AL_RDL pad
6495 0 4B.21.3.3I_20KA : Minimum width of a SLOT region is 2.4um X 2.4um
6503 0 4B.21.3.3J_20KA : Exact space between two metal-8 slot regions is 3um
6508 0 4B.21.3K.a.ME8 : Minimum metal-8 enclosure of metal-8 slot is 2.76um
6526 0 e4B21_3_3Kb_ME8: Maximun metal-8 enclosure of metal-8 slot is 6.76um
6528 0 4B.21.3.3L: SLOT inside of TMV_RDL and LMn must be remove
6565 0 Recommend_4B_21_3_4_ME1:RFPADMK under ME1 structure, must with upper Metal
6576 0 Recommend_4B_21_3_4_ME2:RFPADMK under ME2 structure, must with upper Metal
6585 0 Recommend_4B_21_3_4_ME3:RFPADMK under ME3 structure, must with upper Metal
6592 0 Recommend_4B_21_3_4_ME4:RFPADMK under ME4 structure, must with upper Metal
6597 0 Recommend_4B_21_3_4_ME5:RFPADMK under ME5 structure, must with upper Metal
6600 0 Recommend_4B_21_3_4_ME6:RFPADMK under ME6 structure, must with upper Metal
6602 0 Recommend_4B_21_3_4_ME7:RFPADMK under ME7 structure, must with upper Metal
6603 0 Recommend_4B_21_3_4I_M7 : Exact width of a SLOT region is 1.2um X 1.2um
6604 0 Recommend_4B_21_3_4I_M6 : Exact width of a SLOT region is 1.2um X 1.2um
6605 0 Recommend_4B_21_3_4I_M5 : Exact width of a SLOT region is 1.2um X 1.2um
6606 0 Recommend_4B_21_3_4I_M4 : Exact width of a SLOT region is 1.2um X 1.2um
6607 0 Recommend_4B_21_3_4I_M3 : Exact width of a SLOT region is 1.2um X 1.2um
6608 0 Recommend_4B_21_3_4I_M2 : Exact width of a SLOT region is 1.2um X 1.2um
6609 0 Recommend_4B_21_3_4I_M1 : Exact width of a SLOT region is 1.2um X 1.2um
6617 0 Recommend_4B_21_3_4J_M7_20KA : Exact space between two SLOT regions is 4.2um
6625 0 Recommend_4B_21_3_4J_M6_20KA : Exact space between two SLOT regions is 4.2um
6633 0 Recommend_4B_21_3_4J_M5_20KA : Exact space between two SLOT regions is 4.2um
6641 0 Recommend_4B_21_3_4J_M4_20KA : Exact space between two SLOT regions is 4.2um
6649 0 Recommend_4B_21_3_4J_M3_20KA : Exact space between two SLOT regions is 4.2um
6657 0 Recommend_4B_21_3_4J_M2_20KA : Exact space between two SLOT regions is 4.2um
6665 0 Recommend_4B_21_3_4J_M1_20KA : Exact space between two SLOT regions is 4.2um
6670 0 Recommend_4B_21_3_4Ka_ME7 : Minimum metal-7 enclosure of metal-7 slot is 2.76um
6688 0 Recommend_4B_21_3_4Kb_ME7: Maximun metal-7 enclosure of metal-7 slot is 6.76um
6693 0 Recommend_4B_21_3_4Ka_ME6 : Minimum metal-6 enclosure of metal-6 slot is 2.76um
6711 0 Recommend_4B_21_3_4Kb_ME6: Maximun metal-6 enclosure of metal-6 slot is 6.76um
6716 0 Recommend_4B_21_3_4Ka_ME5 : Minimum metal-5 enclosure of metal-5 slot is 2.76um
6734 0 Recommend_4B_21_3_4Kb_ME5: Maximun metal-5 enclosure of metal-5 slot is 6.76um
6739 0 Recommend_4B_21_3_4Ka_ME4 : Minimum metal-4 enclosure of metal-4 slot is 2.76um
6757 0 Recommend_4B_21_3_4Kb_ME4: Maximun metal-4 enclosure of metal-4 slot is 6.76um
6762 0 Recommend_4B_21_3_4Ka_ME3 : Minimum metal-3 enclosure of metal-3 slot is 2.76um
6780 0 Recommend_4B_21_3_4Kb_ME3: Maximun metal-3 enclosure of metal-3 slot is 6.76um
6785 0 Recommend_4B_21_3_4Ka_ME2 : Minimum metal-2 enclosure of metal-2 slot is 2.76um
6803 0 Recommend_4B_21_3_4Kb_ME2: Maximun metal-2 enclosure of metal-2 slot is 6.76um
6808 0 Recommend_4B_21_3_4Ka_ME1 : Minimum metal-1 enclosure of metal-1 slot is 2.76um
6826 0 Recommend_4B_21_3_4Kb_ME1: Maximun metal-1 enclosure of metal-1 slot is 6.76um
6829 0 Recommend_4B_21_3_4Na_VI1: Minimum space between two VI1 regions in pad area is 0.28um
6834 0 Recommend_4B_21_3_4Oa_VI1: Minimum VI1 to pad edge regions is 0.1um
6839 0 Recommend_4B_21_3_4PQ_VI1: Minimum via1 to metal-1 slot spacing is 0.2um, no via1 on metal-1 slot 
6842 0 Recommend_4B_21_3_4Na_VI2: Minimum space between two VI2 regions in pad area is 0.28um
6847 0 Recommend_4B_21_3_4Oa_VI2: Minimum VI2 to pad edge regions is 0.1um
6852 0 Recommend_4B_21_3_4PQ_VI2: Minimum via2 to metal-2 slot spacing is 0.2um, no via2 on metal-2 slot 
6855 0 Recommend_4B_21_3_4Na_VI3: Minimum space between two VI3 regions in pad area is 0.28um
6860 0 Recommend_4B_21_3_4Oa_VI3: Minimum VI3 to pad edge regions is 0.1um
6865 0 Recommend_4B_21_3_4PQ_VI3: Minimum via3 to metal-3 slot spacing is 0.2um, no via3 on metal-3 slot 
6868 0 Recommend_4B_21_3_4Na_VI4: Minimum space between two VI4 regions in pad area is 0.28um
6873 0 Recommend_4B_21_3_4Oa_VI4: Minimum VI4 to pad edge regions is 0.1um
6878 0 Recommend_4B_21_3_4PQ_VI4: Minimum via4 to metal-4 slot spacing is 0.2um, no via4 on metal-4 slot 
6881 0 Recommend_4B_21_3_4Na_VI5: Minimum space between two VI5 regions in pad area is 0.28um
6886 0 Recommend_4B_21_3_4Oa_VI5: Minimum VI5 to pad edge regions is 0.1um
6891 0 Recommend_4B_21_3_4PQ_VI5: Minimum via5 to metal-5 slot spacing is 0.2um, no via5 on metal-5 slot 
6893 0 Recommend_4B_21_3_4S_VI7_20KA: Minimum space between two VI7 regions is 0.6um.
6895 0 Recommend_4B_21_3_4S_VI6_20KA: Minimum space between two VI6 regions is 0.4um.
6898 0 Recommend_4B_21_3_4T_VI7: Minimum space between two VI7 regions is 0.5um.
6903 0 Recommend_4B.21.3U.a.VI7: Minimum via6 to pad edge regions is 0.1um
6908 0 Recommend_4B_21_3_4VWVI7: Minimum via7 to metal-7 slot spacing is 0.2um, no via7 on metal-7 slot
6911 0 Recommend_4B_21_3_4T_VI6: Minimum space between two VI6 regions is 0.5um.
6916 0 Recommend_4B.21.3U.a.VI6: Minimum via6 to pad edge regions is 0.1um
6921 0 Recommend_4B_21_3_4VWVI6: Minimum via6 to metal-6 slot spacing is 0.2um, no via6 on metal-6 slot
6922 0 Recommend_4B_21_3_4Y_VI1: Minimum VI1 DENSITY under pad open is 12%
6923 0 Recommend_4B_21_3_4Y_VI2: Minimum VI2 DENSITY under pad open is 12%
6924 0 Recommend_4B_21_3_4Y_VI3: Minimum VI3 DENSITY under pad open is 12%
6925 0 Recommend_4B_21_3_4Y_VI4: Minimum VI4 DENSITY under pad open is 12%
6926 0 Recommend_4B_21_3_4Y_VI5: Minimum VI5 DENSITY under pad open is 12%
6927 0 Recommend_4B_21_3_4Y_VI6: Minimum VI6 DENSITY under pad open is 12%
6928 0 Recommend_4B_21_3_4Y_VI7: Minimum VI7 DENSITY under pad open is 12%
6944 0 4B.22.2.2: Only ESD and I/O devices are permitted under BOAC pad
6945 0 4B.22.2C : Minimum width of a metal-8 slot region is 1.2um X 1.2um
6953 0 4B.22.2D : Exact space between two metal-8 slot regions is 2.8um
6958 0 4B.22.2Ea : Minimum metal-8 enclosure of metal-8 slot is 2.76um
6976 0 4B.22.2Eb: Maximun metal-8 enclosure of metal-8 slot is 6.76um
6978 0 4B.22.2F: SLOT inside of TMV_RDL and LMn must be remove
6984 0 4B.24A.a: Minimum width of MMC region is 3.9um
6993 0 4B.24A.b: Maximum MMC width is 100 um
6996 0 4B.24B: Minimum space between two MMC regions is 1.0um
7001 0 4B.24C: Minimum MMCBP ovelap MMC is 0.6um, no MMC outside MMCBP
7004 0 4B.24D: Minimum MMC ovelap TMV_RDL is 0.45um
7006 0 4B.24E: Minimum MMC to unrelated AL_RDL is 0.65um
7012 0 4B.24F: Minimum width of MMCBP region is 5.1um
7015 0 4B.24G: Minimum space between two MMCBP regions is 1.0um
7020 0 4B.24H:Minimum MMCBP ovelap TMV_RDL is 0.45um.
7022 0 4B.24I: Minimum MMC to unrelated Metal8 is 0.4um
7024 0 4B.24J: Minimum MMC to unrelated TMV_RDL is 1.0um
7025 0 4B.24K.a: Minimum and maximum width of TMV_RDL within MMCBP is 3.0um X 3.0um
7031 0 4B.24Kb: Minimum width of a TMV_RDL region is 4.0um X 4.0um
7037 0 4B.24Kc: Minimum width of a TMV_RDL within Fusemark region is 2.3um X 2.3um
7040 0 4B.24L.a: Minimum space between two TMV_RDL regions is 1.6um
7042 0 4B.24L.b: Minimum space between two TMV_RDL regions is 2.0um for TMV_RDL outside MMCBP
7050 0 4B.24M: Minimum width of AL_RDL region is 3.0um
7053 0 4B.24N.a: Minimum space between two AL_RDL regions is 0.9um
7061 0 4B.24O.a: Minimum AL_RDL ovelap TMV_RDL is 0.35um, no TMV_RDL outside AL_RDL
7064 0 4B.24O.b: Minimum AL_RDL ovelap TMV_RDL is 0.5um for TMV_RDL outside MIMBP
7069 0 4B.24P_20KA: Minimum last metal enclosure of TMV_RDL is 0.6um
7075 0 4B.24Q: Minimum Last dummy Metal block layer overlap MMCBP is 0.4um
7090 0 4B.25A:Maximum IND length and width is 320 um
7096 0 4B.25B:Minimum IND length and width is 30 um
7098 0 4B.25C_20KA:Minimum IND to IND spacing is 15.6um
7100 0 4B.25D:Minimum ME8 vertex within IND is 10 um
7101 0 4B.25E:IND shapes must be orthogonal rectangle
7110 0 4B.25G:Maximun ME8 width within IND is 10 um
7112 0 4B.25H_20KA:Minimun spacing IND METAL is 1.5 um
7113 0 4B.25I_20KA:Minimun spacing IND METAL to ME8 is 1.5 um
7121 0 4B.25K:Minimun NWEL to IND METAL is 10 um
7129 0 8.2A: Minimum width of AL_RDL region is 3.0um except fuse area
7135 0 8.2B: Minimum space between two AL_RDL regions (for not over the MIM CAP bottom) is 1.60um
7146 0 8.2C: Minimum space of Al-metal line to Al-metal line is 3um if either/both width > 35um
7152 0 8.2E: Minimum and maximum width of a TMV_RDL region outside fuse, pad and MIMCAP is 4.0um
7155 0 8.2F: Minimum space between two AL_RDL regions outside fuse, pad and MIMCAP is 2um
7160 0 8.2G_20KA: Minimum last copper metal overlap TMV_RDL is 0.6um, no floating RDL_TMV
7165 0 8.2H: Minimum AL_RDL enclosure of TMV_RDL outside fuse, pad and MIMCAP is 0.5um, no floating TMV_RDL
7175 0 8.3A__8.3D.b__8.3E.b: Maximum AL_RDL width without slotting is 20um when length is greater than 30um is 20um
7184 0 8.3B: Minimum and Maximum AL_RDL Slot width are 2um and 5um respectively
7201 0 8.3C: Minimum and Maximum AL_RDL Slot length are 10um and 250um respectively
7204 0 8.3D.a: Minimum space between AL_RDL slot regions is 9um
7209 0 8.3E.a: Minimum slot to Metal edge spacing 9 um
7234 0 SP_4A_1AB:Minimum dimension of an DIFF region is 0.042/0.06um
7235 0 SP_4B_1A:Minimum width of ME1 region is 0.08um
7242 0 SP_4B_1C:Minimum space between ME1 regions is 0.12um
7246 0 SP_4B_1D.a:Minimum ME1 overlap contac is -0.05um
7251 0 SP_OPC_DIFF:SP mark_layer must overlap diffusion OPC_BLOCK_LAYERS
7256 0 SP_OPC_POLY:SP mark_layer must overlap poly OPC_BLOCK_LAYERS
7261 0 SP_OPC_CONT:SP mark_layer must overlap contact OPC_BLOCK_LAYERS
7266 0 SP_OPC_M1:SP mark_layer must overlap metal-1 OPC_BLOCK_LAYERS
7267 0 SP_VTNH:SP mark_layer overlap VTNH layer is not allowed
7268 0 SP_VTPH:SP mark_layer overlap VTPH layer is not allowed
7277 0 SP_OPCT_BLOCK:SP OPC_BLOCK_LAYERS are only for SP SRAM 
7279 0 SP_OPCT_4A_15C:Minimum CONT area in CONTACT_OPC_BLOCK region is 0.0462 um2
7300 0 DP_4B_1A:Minimum width of ME1 region is 0.13um
7301 0 DP_4B_1C:Minimum space between ME1 regions is 0.15um
7305 0 DP_4B_1D.a:Minimum ME1 overlap CONT is -0.05um
7312 0 DP_HS_OPC_DIFF:DP(HS) mark_layer must overlap diffusion OPC_BLOCK_LAYERS
7316 0 DP_HS_OPC_POLY:DP(HS) mark_layer must overlap poly OPC_BLOCK_LAYERS
7332 0 DP_HS_OPC_BLOCK:DP(HS) OPC_BLOCK_LAYERS are only for DP and 2PRFLL SRAM
7336 0 DP_LL_OPC_DIFF:DP(LL) mark_layer must overlap diffusion OPC_BLOCK_LAYERS
7340 0 DP_LL_OPC_POLY:DP mark_layer must overlap poly OPC_BLOCK_LAYERS
7349 0 DP_LL_OPC_BLOCK:DP(LL) OPC_BLOCK_LAYERS are only for DP SRAM
7350 0 DP_LL_VTNH:DP(LL) must overlap VTNH
7351 0 DP_LL_VTPH:DP(LL) must overlap VTPH
7372 0 2PHD_4B_1A:Minimum width of ME1 region is 0.15um
7379 0 2PHD_4B_1C:Minimum space between ME1 regions is 0.16um
7380 0 2PHD_4B_1Da:Minimum ME1 overlap contac is 0um, no CONT outside ME1
7391 0 2PHD.HS_OPC_CELL_BLOCK:2PHD(HS) mark_layer must overlap C_CELL_Block
7392 0 2PHD_LL_OPC_VTNH:2PHD(LL) mark_layer must overlap VTNH
7393 0 e2PHD_LL_OPC_VTPH:2PHD(LL) mark_layer must overlap VTPH
7414 0 2PRF_4B_1A:Minimum width of ME1 region is 0.15um
7421 0 2PRF_4B_1C:Minimum space between ME1 regions is 0.16um
7422 0 2PRF_4B_1D.a:Minimum ME1 overlap contac is 0um, no CONT outside ME1
7423 0 2PRF_VTNH:2PRF mark_layer overlaps VTNH layer is not allowed
7424 0 2PRF_VTPH:2PRF mark_layer overlaps VTPH layer is not allowed
7425 0 2PRF_OPC_CELL_BLOCK:2PRF mark_layer must overlap C_CELL_Block
7446 0 2PRF_1_4B_1C:Minimum space between ME1 regions is 0.16um
7447 0 2PRF_1_4B_1D.a:Minimum ME1 overlap contac is 0um, no CONT outside ME1
7448 0 2PRF_1_VTNH:2PRF mark_layer overlaps VTNH layer is not allowed
7449 0 2PRF_1_VTPH:2PRF mark_layer overlaps VTPH layer is not allowed
7450 0 2PRF_1_OPC_CELL_BLOCK:2PRF mark_layer must overlap C_CELL_Block
7471 0 SPLL_4B_1A:Minimum width of ME1 region is 0.08um
7478 0 SPLL_4B_1C:Minimum space between ME1 regions is 0.12um
7482 0 SPLL_4B_1D.a:Minimum ME1 overlap CONT is -0.05um
7485 0 SPLL_OPC_DIFF:SPLL mark_layer must overlap diffusion OPC_BLOCK_LAYERS
7488 0 SPLL_OPC_POLY:SPLL mark_layer must overlap poly OPC_BLOCK_LAYERS
7491 0 SPLL_OPC_CONT:SPLL mark_layer must overlap contact OPC_BLOCK_LAYERS
7494 0 SPLL_OPC_M1:SPLL mark_layer must overlap metal-1 OPC_BLOCK_LAYERS
7503 0 SPLL.OPC_BLOCK:SPLL OPC_BLOCK_LAYERS are only for SPLL SRAM 
7504 0 SPLL_VTNH:SPLL mark_layer must overlap VTNH
7505 0 SPLL_VTPH:SPLL mark_layer must overlap VTPH
7507 0 SPLL.CONT_4A_15C:Minimum CONT area in CONTACT_OPC_BLOCK region is 0.0462 um2
7528 0 2PRFLL_4B_1A:Minimum width of ME1 region is 0.15um
7529 0 2PRFLL_4B_1C:Minimum space between ME1 regions is 0.16um
7530 0 2PRFLL_4B_1D.a:Minimum ME1 overlap contac is 0um, no CONT outside ME1
7531 0 2PRFLL_VTNH:2PRFLL mark_layer must overlap VTNH
7532 0 2PRFLL_VTPH:2PRFLL mark_layer must overlap VTPH
7553 0 DP2_4B_1A:Minimum width of ME1 region is 0.13um
7560 0 DP2_4B_1C:Minimum space between ME1 regions is 0.15um
7561 0 DP2_4B_1D.a:Minimum ME1 overlap contac is 0um, no CONT outside ME1
7567 0 DP2.HS_OPC_DIFF:DP2(HS) mark_layer must overlap diffusion OPC_BLOCK_LAYERS
7570 0 DP2.HS_OPC_POLY:DP2(HS) mark_layer must overlap poly OPC_BLOCK_LAYERS
7579 0 DP2_HS_OPC_BLOCK:DP2(HS) OPC_BLOCK_LAYERS are only for DP2(HS) SRAM 
7582 0 DP2_LL_OPC.DIFF:DP2(LL) mark_layer must overlap diffusion OPC_BLOCK_LAYERS
7586 0 DP2_LL_OPC.POLY:DP2(LL) mark_layer must overlap poly OPC_BLOCK_LAYERS
7595 0 DP2_LL_OPC_BLOCK:DP2(LL) OPC_BLOCK_LAYERS are only for DP2(LL) SRAM 
7596 0 DP2_LL_VTPH:DP2(LL) mark_layer must overlap VTPH
7597 0 DP2_LL_VTNH:DP2(LL) mark_layer must overlap VTNH
7600 0 OPC_BLOCK_DIFF:diffusion OPC block layer must be covered by SRAM mark layers(SP,SPLL,DP,DP2)
7603 0 OPC_BLOCK_POLY:poly OPC block layer must be covered by SRAM mark layers(SP,SPLL,DP,DP2) 
7606 0 OPC_BLOCK_CONT:contact OPC block layer must be covered by SRAM mark layers(SP,SPLL) 
7609 0 OPC_BLOCK_M1:metal1 OPC block layer must be covered by SRAM mark layers(SP,SPLL) 
7630 0 OPC_BLOCK_C_CELL_BLOCK.1:C_CELL_BLOCK layer must be covered by SRAM mark layers(2PRF_1,2PHD,2PRF,DP1)
7632 0 OPC_BLOCK_C_CELL_BLOCK.2:C_CELL_BLOCK layer overlaps VTNH or VTPH layers is not allowed
7654 0 SP_1_4B_1A:Minimum width of ME1 region is 0.08um
7655 0 SP_1_4B_1C:Minimum space between ME1 regions is 0.12um
7659 0 SP_1_4B_1D.a:Minimum ME1 overlap contac is -0.05um
7663 0 SP_1_OPC_DIFF:SP_1 mark_layer must overlap diffusion OPC_BLOCK_LAYERS
7667 0 SP_1_OPC_POLY:SP_1 mark_layer must overlap poly OPC_BLOCK_LAYERS
7669 0 SP_1_OPC_CONT:SP_1 mark_layer must overlap contact OPC_BLOCK_LAYERS
7673 0 SP_1_OPC_M1:SP_1 mark_layer must overlap metal-1 OPC_BLOCK_LAYERS
7674 0 SP_1_VTNH:SP_1 mark_layer overlap VTNH layer is not allowed
7675 0 SP_1_VTPH:SP_1 mark_layer overlap VTPH layer is not allowed
7688 0 SP_1.OPC_BLOCK:SP_1 OPC_BLOCK_LAYERS are only for SP_1 SRAM 
